### PR TITLE
Fixes to suffix type when creating or editing units.

### LINKED ISSUE #1019: Units of type suffix should have a suffix
### Describe the bug

Currently a unit can be of type suffix but not have a suffix included and the inverse is also possible for both creating and editing a unit. It does not make sense to have such a combination and an admin should be forced to include both or neither. If a suffix is added but the unit is not of type suffix then the admin should be told the type will be changed to suffix. If the unit is of type suffix but there is no suffix unit then the suffix input should become red and an entry required before saving.

### Screenshots

Examples for create a unit are shown but edit behaves similarly.

Screenshot 2023-09-25 073325

Screenshot 2023-09-25 073307

### Additional context

Currently the admin help warns about doing this so hopefully it will not happen but this fix would mean the documentation can be updated to say it cannot happen.

### PR DESCRIPTION
**Pull request by Jake-Bodin**
# Description

Changes to use effect, changing submit, suffix, and typeofUnit, in createUnit and editUnit files to complete the Issue #1019 
Also added a formatted message to data.js

Fixes #1019 

## Type of change

(Check the ones that apply by placing an "x" instead of the space in the [ ] so it becomes [x])

- [ ] Note merging this changes the database configuration.
- [ ] This change requires a documentation update

## Checklist

(Note what you have done by placing an "x" instead of the space in the [ ] so it becomes [x]. It is hoped you do all of them.)

- [ X] I have followed the [OED pull request](https://openenergydashboard.github.io/developer/pr.html) ideas
- [ ] I have removed text in ( ) from the issue request
- [ X] You acknowledge that every person contributing to this work has signed the [OED Contributing License Agreement](https://openenergydashboard.github.io/developer/cla.html) and each author is listed in the Description section.

## Limitations

(Describe any issues that remain or work that should still be done.)

### CODE REVIEW

File: src/client/app/components/unit/CreateUnitModalComponent.tsx [hunk 1]
```diff
@@ -69,11 +69,13 @@ export default function CreateUnitModalComponent() {
...
 		Name cannot be blank
 		Sec in Rate must be greater than zero
+		If type of unit is suffix their must be a suffix
 	*/
 	const [validUnit, setValidUnit] = useState(false);
 	useEffect(() => {
-		setValidUnit(state.name !== '' && state.secInRate > 0);
-	}, [state.name, state.secInRate]);
+		setValidUnit(state.name !== '' && state.secInRate > 0 &&
+			(state.typeOfUnit !== UnitType.suffix || (state.typeOfUnit === UnitType.suffix && state.suffix !== '')));
```
Comment (huss) [inline src/client/app/components/unit/CreateUnitModalComponent.tsx]: The first check to make sure it is unequal suffix does not seem to be needed. It also does not follow the other checks in this file. I changed it and did not see any issue. Am I missing something?

This also applies to edit.

**Review by huss — CHANGES_REQUESTED** [review]
Thanks to @Jake-Bodin for another pull request. It worked well and no issues were encountered. I make one comment on the code that should be addressed.

File: src/client/app/components/unit/CreateUnitModalComponent.tsx (hunk 1 above)
Comment (Jake-Bodin) [reply src/client/app/components/unit/CreateUnitModalComponent.tsx]: It's redundant, I believe i did that early on because I was looking at this line in the CreateMeter file
             (state.area === 0 || (state.area > 0 && state.areaUnit !== AreaUnitType.none
Which is unnecessary in this case.

File: src/client/app/components/unit/CreateUnitModalComponent.tsx [hunk 2]
```diff
@@ -69,11 +69,13 @@ export default function CreateUnitModalComponent() {
...
 		Name cannot be blank
 		Sec in Rate must be greater than zero
+		If type of unit is suffix their must be a suffix
 	*/
 	const [validUnit, setValidUnit] = useState(false);
 	useEffect(() => {
-		setValidUnit(state.name !== '' && state.secInRate > 0);
-	}, [state.name, state.secInRate]);
+		setValidUnit(state.name !== '' && state.secInRate > 0 &&
+			(state.typeOfUnit === UnitType.suffix && state.suffix !== ''));
```
Comment (huss) [inline src/client/app/components/unit/CreateUnitModalComponent.tsx]: I think the logic is off here. I believe the correct logic is
```
	setValidUnit(state.name !== '' && state.secInRate > 0 &&
			(state.typeOfUnit !== UnitType.suffix || state.suffix !== ''));
```
I found the current logic did not allow saving if you removed the suffix and then changed the type of unit to non-suffix. Let me know if you agree and, if so, change in both files.

Comment (Jake-Bodin) [reply src/client/app/components/unit/CreateUnitModalComponent.tsx]: Your correct I see the same issue and after using your logic it seems to be working fine I apologize.

**Comment by huss** [comment]
Thanks to @Jake-Bodin for making these changes. The PR is fine and ready to merge. Note it will be held for a little while until the pending Vite PR is (hopefully) merged.

**Review by huss — APPROVED** [review]

**Comment by huss** [comment]
The merge after review only adds in approved code from development so this PR is still fine and queue to be merged.
