### PR TITLE
Fix tests destroying the database.

### LINKED ISSUE #345: Running tests breaks production database
To reproduce: Create a production DB (e.g. with the init script).

Check that there are entries in a table; here I look at meters.

```
# leo ∈ rochallor in ~/Projects/OED on git::meter-update-display-optional x
λ docker-compose exec database psql -U oed
psql (9.6.10)
Type "help" for help.

oed=> select * from meters;
 id |      name      |  ipaddress  | enabled | displayable | meter_type
----+----------------+-------------+---------+-------------+------------
  1 | Aldrich 3rd    | 144.89.8.13 | t       | t           | mamac
  2 | Aldrich Ground | 144.89.8.12 | t       | t           | mamac
  3 | Aldrich Main   | 144.89.8.14 | t       | t           | mamac
  4 | Maurer Main    | 144.89.8.22 | t       | t           | mamac
  5 |  Maurer 1st    | 144.89.8.21 | t       | t           | mamac
  6 | Chapin Main    | 144.89.8.15 | t       | t           | mamac
  7 | Chapin 3rd     | 144.89.8.17 | t       | t           | mamac
  8 | Chapin Misc.   | 144.89.8.16 | t       | t           | mamac
  9 | Aldrich 1st    | 144.89.8.11 | t       | t           | mamac
 10 | Aldrich 2nd    | 144.89.8.10 | t       | t           | mamac
 11 | Maurer 3rd     | 144.89.8.19 | t       | t           | mamac
 12 | Chapin 2nd     | 144.89.8.18 | t       | t           | mamac
 13 | Maurer 2nd     | 144.89.8.20 | t       | t           | mamac
(13 rows)
```

Then, run the tests:

```
# leo ∈ rochallor in ~/Projects/OED on git::meter-update-display-optional x
λ docker-compose run --rm web npm run test
[... all tests pass ...]
```

Now, run the same query:

```
# leo ∈ rochallor in ~/Projects/OED on git::meter-update-display-optional x  C:130
λ docker-compose exec database psql -U oed
psql (9.6.10)
Type "help" for help.

oed=> select * from meters;
 id | name | ipaddress | enabled | displayable | meter_type
----+------+-----------+---------+-------------+------------
(0 rows)
```

### PR DESCRIPTION
**Pull request by NoraCodes**
This involved changing all imports of the db global to imports
of a getDB function which is a relatively transparent wrapper
over that global. It does, however, check for config changes and
enforce a total transition to any newly configured DB.

Performance impact should be minimial as that code will mostly be
skipped and the tracing JIT should inline the function fairly
rapidly.

Closes #345

### CODE REVIEW

File: src/server/test/db/common.js [hunk 1]
```diff
@@ -16,16 +16,23 @@ config.database = {
...
 log.level = LogLevel.SILENT;
 
-const { db, createSchema } = require('../../models/database');
-
 async function recreateDB() {
+	// Just transfer connection if needed.
+	getDB();
+	if (currentDB() === process.env.OED_DB_DATABASE) {
+		// tslint:disable-next-line no-console
+		console.error(`Refusing to destroy production database ${currentDB()} for tests; should be using ${config.database.database}.`)
```
Comment (shuheif) [inline src/server/test/db/common.js]: The Travis test is returning an error from this line showing "Refusing to destroy production database travis_ci_test for tests; should be using travis_ci_test." config.database.database refers to process.env.OED_DB_DATABASE in src/server/config.js and they are the same. I guess either the if statement or the console error message is mistaken.

**Comment by shuheif** [comment]
It looks good to me now.

**Comment by NoraCodes** [comment]
Awesome, thanks! Can you approve?

**Review by shuheif — APPROVED** [review]
