### PR TITLE
issue #1210 resolved

### LINKED ISSUE #1210: unit with suffix has displayable of none
### Describe the bug

If a unit has a suffix then its displayable should be none. Currently unit create and edit do not enforce this. This shows it does force the type of unit but not the displayable:

image

### Expected behavior

Meter do something similar as seen in:

image

and units should warn and set to none.

### Additional context

None

### PR DESCRIPTION
**Pull request by danielshid**
# Description

Now, when a unit is created or edited, if there is input in the suffix box, it will display an error message underneath the displayable box and force the displayable to be none.

Fixes #1210

## Type of change

- [ ] Note merging this changes the database configuration.
- [x] This change requires a documentation update

## Checklist

- [x] I have followed the [OED pull request](https://openenergydashboard.github.io/developer/pr.html) ideas
- [x] I have removed text in ( ) from the issue request
- [x] You acknowledge that every person contributing to this work has signed the [OED Contributing License Agreement](https://openenergydashboard.github.io/developer/cla.html) and each author is listed in the Description section.

## Limitations

N/A

### CODE REVIEW

File: src/client/app/translations/data.ts [hunk 1]
```diff
@@ -153,6 +153,7 @@ const LocaleTranslationData = {
 		"error.bounds": "Must be between {min} and {max}.",
 		"error.displayable": "Displayable will be set to false because no unit is selected.",
 		"error.displayable.meter": "Meter units will set displayable to none.",
+		"error.displayable.suffix.input": "Suffix input will set displayable to none.",
```
Comment (huss) [inline src/client/app/translations/data.ts:156]: This key appears to be missing from es (Spanish).

**Review by huss — CHANGES_REQUESTED** [review]
Thanks to @danielshid for another PR. Review found it works as desired. I have made one small comment to look at. Also, I don't yet know why but the automated tests are not running on GitHub for PRs. I have manually run locally and no issues were found.

**Comment by huss** [comment]
I merged in development to resolve a conflict. Not sure why your merge did not get this commit.

**Review by huss — CHANGES_REQUESTED** [review]
@danielshid The changes look good and run as expected. However, when I resolved the merge conflict and the test ran they failed because of using spaces instead of tabs for indenting. Can you please fix these (you can use VSC to convert indenting to tabs and spaces to tabs by clicking the tab size in the bottom, right part of the window).

**Review by huss — APPROVED** [review]
