### PR TITLE
Map chart translate text

### LINKED ISSUE #1169: translate when no map displayed
### Describe the bug

"There\'s not an available map" is not translated and in two places in the code.

### Additional context

It might be easy to address this as part of issue #1145 but not necessary.

### PR DESCRIPTION
**Pull request by hazeltonbw**
# Description

Added translation for occurrences where there is no map.
Fixes #1169 
This PR supersedes PR #1311 due to the irrelevant commits that were associated with it.
This PR includes only the necessary changes to fix the issue.

## Type of change

- [ ] Note merging this changes the database configuration.
- [ ] This change requires a documentation update

## Checklist

- [x] I have followed the [OED pull request](https://openenergydashboard.github.io/developer/pr.html) ideas
- [x] I have removed text in ( ) from the issue request
- [x] You acknowledge that every person contributing to this work has signed the [OED Contributing License Agreement](https://openenergydashboard.github.io/developer/cla.html) and each author is listed in the Description section.

### CODE REVIEW

File: src/client/app/translations/data.ts [hunk 1]
```diff
@@ -321,6 +321,7 @@ const LocaleTranslationData = {
 		"map.new.upload": "Upload map image to begin.",
 		"map.notify.calibration.needed": "Calibration needed before display",
 		"map.upload.new.file": "Redo",
+		"map.unavailable": "There's not an available map",
```
Comment (huss) [inline src/client/app/translations/data.ts:323]: This should be one line up so alphabetical and mirror other languages.

**Review by huss — DISMISSED** [review]
removed

**Review by huss — CHANGES_REQUESTED** [review]
Thanks to @hazeltonbw for addressing this issue. I made one small comment. Other than that, everything looks fine and works as expected.

**Review by huss — APPROVED** [review]
