### PR TITLE
Maps now work with groups

### LINKED ISSUE #569: maps should work with groups
It should work with groups in the same way it does with meters and similarly to other graphics. Note that src/client/app/containers/ChartDataSelectContainer.ts checks disabled meters but not groups so this also needs to be added.

### LINKED ISSUE #579: groups sometimes fail to show up
This is a little tricky to see. It only seems to happen for some groups when the meter and group overlap in the sense that the meter is in the group. It does not happen for all groups of this type and, so far, it has only been for one of the meters of this type. When it does happen, the group is not displayed on the bar graphic. It does not seem to matter if you add other meters but it seems important that you choose the meter first or the group that is already displayed remains. You can remove any meter other than the special one and the group does not show. However, as soon as your remove that meter from graphing the group reappears no matter when in the process of removing the meters it happens.

### PR DESCRIPTION
**Pull request by jina2k**
# Description
Fixes #569 
So previously, displaying a map would only work with meters, and now maps can work with groups as well, as long as you put GPS coordinates into the database directly. 
Fixes #579 , I fixed this bug by changing it to accurately pull using groupID instead of meterID
## Type of change

- [ ] Note merging this changes the node modules
- [ ] Note merging this changes the database configuration.
- [ ] This change requires a documentation update

## Checklist

- [x] I have followed the [OED pull request](https://openenergydashboard.github.io/developer/pr.html) ideas
- [x] I have removed text in ( ) from the issue request

## Limitations
As mentioned above, this implementation can only be seen visually by inserting gps values directly into the database; ie; updating gps point values in the groups table. In the future, we will need to implement UI for the admin to be able to edit GPS values in the database for the groups from the website.

### CODE REVIEW

File: src/client/app/actions/groups.ts [hunk 1]
```diff
@@ -282,7 +282,9 @@ export function submitGroupInEditingIfNeeded() {
 			const group = {
 				name: rawGroup.name,
 				childGroups: rawGroup.childGroups,
-				childMeters: rawGroup.childMeters
+				childMeters: rawGroup.childMeters,
+				gps: rawGroup.gps,
```
Comment (huss) [inline src/client/app/actions/groups.ts:286]: While this is fine for the long-term, I just want to note that I think that neither gps nor displayable are currently set in the group create/edit so they will remain empty until we create a group edit page.

File: src/client/app/containers/ChartDataSelectContainer.ts [hunk 2]
```diff
@@ -79,15 +81,39 @@ function mapStateToProps(state: State) {
 			}
 		});
 		// filter groups - this is not yet done as groups do not show up on maps yet.
+		sortedGroups.forEach(group => {
```
Comment (huss) [inline src/client/app/containers/ChartDataSelectContainer.ts:84]: The comment above about not being done yet seems out of date. I might also add that it follows the logic for meters above so see those comments.

File: src/client/app/containers/ChartDataSelectContainer.ts [hunk 3]
```diff
@@ -79,15 +81,39 @@ function mapStateToProps(state: State) {
...
+			const gps = state.groups.byGroupID[group.value].gps;
+			const origin = state.maps.byMapID[state.maps.selectedMap].origin;
```
Comment (huss) [inline src/client/app/containers/ChartDataSelectContainer.ts]: You did not start this but looking at the logic I think that origin & opposite cannot change while this function is running. Thus, they should probably be calculated outside the loops (after imageDimensions) so not redone with each group. If done, the same change should be applied to meter loop above.

File: src/client/app/containers/ChartDataSelectContainer.ts [hunk 4]
```diff
@@ -79,15 +81,39 @@ function mapStateToProps(state: State) {
...
+			const opposite = state.maps.byMapID[state.maps.selectedMap].opposite;
+
+			if (origin !== undefined && opposite !== undefined && gps !== undefined && gps !== null) {
```
Comment (huss) [inline src/client/app/containers/ChartDataSelectContainer.ts:86]: In a similar light, the first two parts of the if on origin and opposite could be used outside the loop and then do scaleOfMap. The last two parts on gps stay here to protect the rest of the calculation.

File: src/client/app/containers/ChartDataSelectContainer.ts [hunk 5]
```diff
@@ -79,15 +81,39 @@ function mapStateToProps(state: State) {
...
+				const scaleOfMap = calculateScaleFromEndpoints(origin, opposite, imageDimensionNormalized);
+				const meterGPSInUserGrid: CartesianPoint = gpsToUserGrid(imageDimensionNormalized, gps, origin, scaleOfMap);
```
Comment (huss) [inline src/client/app/containers/ChartDataSelectContainer.ts]: Should this be named groupGPSInUserGrid instead of meterGPSInUserGrid since I think it involves the group?

File: src/client/app/containers/ChartDataSelectContainer.ts [hunk 6]
```diff
@@ -79,15 +81,39 @@ function mapStateToProps(state: State) {
...
+				if (!(itemMapInfoOk(group.value, DataType.Group, state.maps.byMapID[state.maps.selectedMap], gps) &&
+					meterDisplayableOnMap(imageDimensionNormalized, meterGPSInUserGrid))) {
+					group.disabled = true;
+					disableGroups.push(group.value);
+				}
+			} else {
+				// Lack info on this map so skip. This is mostly done since TS complains about the undefined possibility.
```
Comment (huss) [inline src/client/app/containers/ChartDataSelectContainer.ts]: I'm wondering if the comment on mostly done for TS is now obsolete since disabledGroups is used below.

File: src/client/app/containers/ChartDataSelectContainer.ts [hunk 7]
```diff
@@ -79,15 +81,39 @@ function mapStateToProps(state: State) {
...
+		sortedGroups.forEach(group => {
+			const gps = state.groups.byGroupID[group.value].gps;
+			const origin = state.maps.byMapID[state.maps.selectedMap].origin;
+			const opposite = state.maps.byMapID[state.maps.selectedMap].opposite;
+
+			if (origin !== undefined && opposite !== undefined && gps !== undefined && gps !== null) {
+				const scaleOfMap = calculateScaleFromEndpoints(origin, opposite, imageDimensionNormalized);
+				const meterGPSInUserGrid: CartesianPoint = gpsToUserGrid(imageDimensionNormalized, gps, origin, scaleOfMap);
+				if (!(itemMapInfoOk(group.value, DataType.Group, state.maps.byMapID[state.maps.selectedMap], gps) &&
+					meterDisplayableOnMap(imageDimensionNormalized, meterGPSInUserGrid))) {
```
Comment (huss) [inline src/client/app/containers/ChartDataSelectContainer.ts]: I think here and in function declaration in calibration.ts, meterDisplayableOnMap should become itemDisplayableOnMap since now used for both meter & groups. This makes it parallel to change for itemMapInfoOk.

File: src/client/app/containers/ChartDataSelectContainer.ts [hunk 8]
```diff
@@ -79,15 +81,39 @@ function mapStateToProps(state: State) {
...
 	}
 
-	const selectedGroups = state.graph.selectedGroups.map(groupID => (
-		{
-			label: state.groups.byGroupID[groupID] ? state.groups.byGroupID[groupID].name : '',
-			value: groupID,
-			disabled: false
-		} as SelectOption
-	));
+	const selectedGroups = state.graph.selectedGroups.map(groupID => {
```
Comment (huss) [inline src/client/app/containers/ChartDataSelectContainer.ts]: The group logic should come after meters so same order as all above.

File: src/client/app/utils/calibration.ts [hunk 9]
```diff
@@ -65,16 +66,18 @@ export interface Dimensions {
...
  */
-export function meterMapInfoOk(meterInfo: { gps?: GPSPoint, meterID: number }, map: MapMetadata): boolean {
+export function itemMapInfoOk(itemID: number, type: DataType, map: MapMetadata, gps?: GPSPoint): boolean {
 	if (map === undefined) { return false; }
-	if ((meterInfo.gps === null || meterInfo.gps === undefined) || map.origin === undefined || map.opposite === undefined) { return false; }
-	if (!isValidGPSInput(`${meterInfo.gps.latitude},${meterInfo.gps.longitude}`)) {
-		logToServer('error', `Found invalid meter gps stored in database, id = ${meterInfo.meterID}`);
+	if ((gps === null || gps === undefined) || map.origin === undefined || map.opposite === undefined) { return false; }
+	if (!isValidGPSInput(`${gps.latitude},${gps.longitude}`)) {
+		logToServer('error', `Found invalid ${type === DataType.Meter ? 'meter' : 'group'} gps stored in database, id = ${itemID}`);
```
Comment (huss) [inline src/client/app/utils/calibration.ts]: During testing I realized that there is a bug that was not due to any change in the PR. The logToServer call returns a function. We need () at the end so it becomes:
logToServer('error', `Found invalid ${type === DataType.Meter ? 'meter' : 'group'} gps stored in database, id = ${itemID}`)();
so the function returned is executed and the logging occurs. I was able to validate this works properly for both meter & group by setting at least one of the GPS values to be too large, i.e., 400, and then running the code. It causes a popup warning too (since it is reusing the calibration functions) but I think that is okay for now since this really should not happen (a GPS input error should be caught before it is entered into the DB). It also logs to log.txt as was the desire.
Also, src/client/app/components/maps/MapCalibrationInitiateComponent.tsx has the same issue on line 93 which needs to become:
logToServer('error', `Error, map source image uploading: ${err}`)();
I searched and all other uses of logToServer are in actions that dispatch them so I think all the others are okay.

File: src/client/app/containers/MapChartContainer.ts [hunk 10]
```diff
@@ -123,6 +123,59 @@ function mapStateToProps(state: State) {
 				}
 			}
 
+			for (const groupID of state.graph.selectedGroups) {
```
Comment (huss) [inline src/client/app/containers/MapChartContainer.ts:126]: Most of the comments from meter loop similar to this one are included. The ones on the first few lines are missing (and edit as needed for meters).

File: src/client/app/containers/MapChartContainer.ts [hunk 11]
```diff
@@ -123,6 +123,59 @@ function mapStateToProps(state: State) {
...
+				const byGroupID = state.readings.bar.byGroupID[groupID];
+				const gps = state.groups.byGroupID[groupID].gps;
+				if (gps !== undefined && gps !== null) {
+					// Convert the gps value to the equivalent Plotly grid coordinates on user map.
+					// First, convert from GPS to grid units. Since we are doing a GPS calculation, this happens on the true north map.
+					// It must be on true north map since only there are the GPS axis parallel to the map axis.
+					// To start, calculate the user grid coordinates (Plotly) from the GPS value. This involves calculating
+					// it coordinates on the true north map and then rotating/shifting to the user map.
+					const meterGPSInUserGrid: CartesianPoint = gpsToUserGrid(imageDimensionNormalized, gps, origin, scaleOfMap);
```
Comment (huss) [inline src/client/app/containers/MapChartContainer.ts]: I think the variable with meter should become group here.

File: src/client/app/actions/barReadings.ts [hunk 12]
```diff
@@ -44,7 +44,7 @@ export function shouldFetchMeterBarReadings(state: State, meterID: number, timeI
  * @returns {boolean} True if the readings for the given group, time, and duration are missing; false otherwise.
  */
 export function shouldFetchGroupBarReadings(state: State, groupID: number, timeInterval: TimeInterval, barDuration: moment.Duration): boolean {
-	const readingsForID = state.readings.bar.byMeterID[groupID];
+	const readingsForID = state.readings.bar.byGroupID[groupID];
```
Comment (huss) [inline src/client/app/actions/barReadings.ts:47]: I think this is an okay change but it does not seem to relate to the map group changes. (Same thought for compareReadings.ts) Is it correct that this fixes a mistake that has been in the code for a while? I did some quick testing (not extensive) and it may be the case that issue #579 is fixed by this change. Would you be willing to see if it seems gone for you and link that issue if it is the case? (Also add comment to issue that think okay but it has had to find so closing for now.)

**Comment by huss** [comment]
I think these changes may have fixed issue #600. Could you see if that is the case for you? If so, please link that issue to this PR.

**Review by huss — CHANGES_REQUESTED** [review]
This works as expected and is good work. I have made some comments to address ideas in the code and some that I saw while reviewing the PR but not really part of it. Could you please look them over and make the changes as is appropriate.

**Comment by jina2k** [comment]
> I think these changes may have fixed issue #600. Could you see if that is the case for you? If so, please link that issue to this PR.

After attempting to replicate this issue, it appears that this issue is still not fixed, so I will leave it unresolved.

**Comment by huss** [comment]
> > I think these changes may have fixed issue #600. Could you see if that is the case for you? If so, please link that issue to this PR.
> 
> After attempting to replicate this issue, it appears that this issue is still not fixed, so I will leave it unresolved.

Okay. If you know how to reproduced the issue then please put the directions into issue #600 so it will be easier to continue to work on it. Thanks for being careful to determine it is still there.

File: src/client/app/actions/groups.ts (hunk 1 above)
Comment (jina2k) [reply src/client/app/actions/groups.ts:286]: Noted, I will leave it as is for now as the group edit page will be added eventually

File: src/client/app/containers/ChartDataSelectContainer.ts (hunk 2 above)
Comment (jina2k) [reply src/client/app/containers/ChartDataSelectContainer.ts:84]: changed comment to account for above code

File: src/client/app/containers/ChartDataSelectContainer.ts (hunk 3 above)
Comment (jina2k) [reply src/client/app/containers/ChartDataSelectContainer.ts]: took out origin and opposite for both meters and groups

File: src/client/app/containers/ChartDataSelectContainer.ts (hunk 4 above)
Comment (jina2k) [reply src/client/app/containers/ChartDataSelectContainer.ts:86]: scaleOfMap was left in the if statement as it still required origin and opposite to be defined, and I figured const variables were better than using let variables. It's also possible to have the entire foreach loop for both meters and groups to be in an if statement, and then define it this way, but I left it as is for now. This could potentially simplify the else statement where origin,opposite, or gps are undefined. Not sure which method looks better to you.

File: src/client/app/containers/ChartDataSelectContainer.ts (hunk 5 above)
Comment (jina2k) [reply src/client/app/containers/ChartDataSelectContainer.ts]: renamed variable name to groupGPSInUserGrid

File: src/client/app/containers/ChartDataSelectContainer.ts (hunk 6 above)
Comment (jina2k) [reply src/client/app/containers/ChartDataSelectContainer.ts]: I think this piece of code is still necessary, though I'm not sure the comment accurately displays the use. If the GPS coordinates are still undefined as such with groups/meter, I suppose it is still valid behavior to disable the group/meter from being displayed.

File: src/client/app/containers/ChartDataSelectContainer.ts (hunk 7 above)
Comment (jina2k) [reply src/client/app/containers/ChartDataSelectContainer.ts]: renamed function to itemDisplayableOnMap

File: src/client/app/containers/ChartDataSelectContainer.ts (hunk 8 above)
Comment (jina2k) [reply src/client/app/containers/ChartDataSelectContainer.ts]: moved the code to account for the meter -> group order

File: src/client/app/utils/calibration.ts (hunk 9 above)
Comment (jina2k) [reply src/client/app/utils/calibration.ts]: added () to both function calls as mentioned

File: src/client/app/containers/MapChartContainer.ts (hunk 10 above)
Comment (jina2k) [reply src/client/app/containers/MapChartContainer.ts:126]: added comments and edited it for groups

File: src/client/app/containers/MapChartContainer.ts (hunk 11 above)
Comment (jina2k) [reply src/client/app/containers/MapChartContainer.ts]: renamed variable name

File: src/client/app/actions/barReadings.ts (hunk 12 above)
Comment (jina2k) [reply src/client/app/actions/barReadings.ts:47]: issue #579 is fixed supposedly, if my recreation of the bug is right. I will add it into this pull request as well.

**Comment by huss** [comment]
> > > I think these changes may have fixed issue #600. Could you see if that is the case for you? If so, please link that issue to this PR.
> > 
> > 
> > After attempting to replicate this issue, it appears that this issue is still not fixed, so I will leave it unresolved.
> 
> Okay. If you know how to reproduced the issue then please put the directions into issue #600 so it will be easier to continue to work on it. Thanks for being careful to determine it is still there.

I think I was just lucky or got it wrong, but I agree the bug is still there.

**Review by huss — APPROVED** [review]

**Comment by huss** [comment]
The changes are great and this PR is ready to go. Thanks for another good PR.
