### PR TITLE
Multiple Fixes: Fixes issues with Modals (Issue #794)

### LINKED ISSUE #794: lost help on pages with cards
### Describe the bug

If you are on one of the new pages that uses modals (unit, meter, conversion) then the help icon works fine when you first load the page. However, once you have a modal popup (edit or create) then it will not work until you leave the page and return. The help on the modal popup works fine.

### To Reproduce

1. To to one of the modal pages.
2. Click the help icon to see it works.
3. Click to edit or create a new item.
4. After the modal pops up you can see the help works. You don't need to actually change anything on the page. Leave the popup in any way.
5. The help icon on the card page will not work.
6. Go to any other page and return and the help icon now works.

### Expected behavior

The help icons should always work.

### Additional context

None

### PR DESCRIPTION
**Pull request by Donny-Guo**
Fixes #794

# Description

(This resolves the tooltips not being shown after displaying a modal. Also fixes an issue with the Menu Modal not allowing tooltips for mobile users on the front page.)

## Type of change

(Check the ones that apply by placing an "x" instead of the space in the [ ] so it becomes [x])

- [ ] Note merging this changes the node modules
- [ ] Note merging this changes the database configuration.
- [ ] This change requires a documentation update

## Checklist

(Note what you have done by placing an "x" instead of the space in the [ ] so it becomes [x]. It is hoped you do all of them.)

- [x] I have followed the [OED pull request](https://openenergydashboard.github.io/developer/pr.html) ideas
- [x] I have removed text in ( ) from the issue request

## Limitations

No limitations.

### CODE REVIEW

File: src/client/app/components/MenuModalComponent.tsx [hunk 1]
```diff
@@ -60,7 +60,7 @@ export default class MenuModalComponent extends React.Component<MenuModalProps,
 							<p style={labelStyle}>
 								<FormattedMessage id='navigation' />:
 							</p>
-							<HeaderButtonsContainer  showCollapsedMenuButton={false} />
+							<HeaderButtonsContainer  showCollapsedMenuButton={false} isModal />
```
Comment (huss) [inline src/client/app/components/MenuModalComponent.tsx]: This may well be my lack of knowledge about this so just let me know. I'm confused about isModal in two ways. First, it does not seem to be set in this file. Is it assuming a default? Second, it is supplying this value the HeaderButtonsContainer but that does not seem to be part of its props. However, it all seems to work great.

**Comment by huss** [comment]
Thanks to @ConlynPattison and @Donny-Guo for their first PR. OED appreciates your contribution. From the records I see, neither of you have agreed to the [OED CLA](https://openenergydashboard.github.io/developer/cla.html). The project needs that before we can accept your contribution. Please let me know if you have any questions or if you think I missed your CLA. Thanks.

**Review by huss — CHANGES_REQUESTED** [review]
Thank you to @Donny-Guo and @ConlynPattison for this PR. I tried hard to get the failure to occur that was described in the issue but could not. It seems to work perfectly. I did leave one comment that I would like to better understand. I'm mostly requesting changes to hold for the needed CLA (see comment).

**Comment by huss** [comment]
The CLAs are now good. Thanks for the quick work. Now I would just like your insights into the one comment where I was unsure about the code.

**Comment by ConlynPattison** [comment]
@huss thank you for the feedback, and both @Donny-Guo and I have now filled out the OED CLA. Regarding the props for the HeaderButtonsContainer, we could add the isModal property to the file to remain consistent with the showCollapsedMenuButton as a 'ownProps' property. It seems to react to the prop values in the Component file without that addition, but I understand how that could be confusing.

In the MenuModalComponent you've snipped, if I understand your first confusion correctly, it is set to ={true} in that component render call. You could explicitly set the property with isModal={true}, but it is not needed to achieve the same value.

**Comment by huss** [comment]
> @huss thank you for the feedback, and both @Donny-Guo and I have now filled out the OED CLA. Regarding the props for the HeaderButtonsContainer, we could add the isModal property to the file to remain consistent with the showCollapsedMenuButton as a 'ownProps' property. It seems to react to the prop values in the Component file without that addition, but I understand how that could be confusing.

Thanks to @ConlynPattison for the explanation and quick reply. I think consistency and being as transparent as possible are good. Thus, I lean toward adding this if you are willing.

> In the MenuModalComponent you've snipped, if I understand your first confusion correctly, it is set to ={true} in that component render call. You could explicitly set the property w

Again, I lean toward showing the intended value when there might be any doubt. I think the code always wants true so I would show that.

**Comment by huss** [comment]
Thanks for making the suggested change. The code looks good and is ready to merge.

**Review by huss — APPROVED** [review]
