### PR TITLE
Connection strategy changeover - pre 0.5 blocker clearing

### LINKED ISSUE #347: "conn is not a function" error when creating a new group
I'm getting "conn is not a function" error when creating a new group. This is because getDB func should not have () when it is used as conn variable inside methods. 
Related to #346 

`[ERROR@2018-09-21T19:00:34.895Z] Error while inserting new group BatchError 
    stat: { total: 5, succeeded: 0, failed: 5, duration: 2 }
    errors: [
        0: TypeError: conn is not a function
            at Function.getByID (/usr/src/app/src/server/models/Meter.js:76:21)
`

### LINKED ISSUE #405: Recently hidden meters still visible on home page.
After hiding a meter and logging out, the meter is still visible on home until page is refreshed.

### PR DESCRIPTION
**Pull request by NoraCodes**
Yay, here's the big refactor and test block that gives us working database connections! In essence it moves the connection responsibility from the point of use to the point of call; e.g. data base connections are no longer generated in models but rather are generated in routes, in tests, and in scripts.

This gives a lot more control over which DB connection is used.

Once this is merged 0.5 is not far behind. This includes all code for, and thus obviates and closes #399, closes #347, closes #363, closes #350, and closes #335

Also closes #405

### CODE REVIEW

File: src/server/log.js [hunk 1]
```diff
@@ -2,9 +2,12 @@
  * License, v. 2.0. If a copy of the MPL was not distributed with this
  * file, You can obtain one at http://mozilla.org/MPL/2.0/. */
 
+// TODO: This subsystem should make its own database connections.
+
```
Comment (huss) [inline src/server/log.js]: Is this okay and comment correct?

File: src/server/models/Group.js [hunk 2]
```diff
@@ -23,21 +22,21 @@ class Group {
 	 * Returns a promise to create all the groups tables.
 	 * @returns {Promise<>}
 	 */
-	static createTables() {
-		return getDB().none(sqlFile('group/create_groups_tables.sql'));
+	static createTables(conn) {
```
Comment (huss) [inline src/server/models/Group.js:26]: Should there be a comment about conn is one used as in other places?

File: src/server/models/Meter.js [hunk 3]
```diff
@@ -28,37 +27,37 @@ class Meter {
 	 * Returns a promise to create the meters table.
 	 * @return {Promise.<>}
 	 */
-	static createTable() {
-		return getDB().none(sqlFile('meter/create_meters_table.sql'));
+	static createTable(conn) {
```
Comment (huss) [inline src/server/models/Meter.js:33]: @param for conn?

File: src/server/models/Meter.js [hunk 4]
```diff
@@ -28,37 +27,37 @@ class Meter {
...
 	}
 
 	/**
 	 * Returns a promise to create the meter_type type.
 	 * This needs to be run before Meter.createTable().
 	 * @return {Promise<void>}
 	 */
-	static createMeterTypesEnum() {
-		return getDB().none(sqlFile('meter/create_meter_types_enum.sql'));
+	static createMeterTypesEnum(conn) {
```
Comment (huss) [inline src/server/models/Meter.js:43]: @param for conn?

File: src/server/models/Preferences.js [hunk 5]
```diff
@@ -24,28 +23,33 @@ class Preferences {
...
+	 *
+	 * @param conn is the connection to use.
+	 */
+	static async get(conn) {
+		const row = await conn.one(sqlFile('preferences/get_preferences.sql'));
 		return Preferences.mapRow(row);
 	}
 
-	static async update(newPreferences) {
+	static async update(conn, newPreferences) {
```
Comment (huss) [inline src/server/models/Preferences.js]: @param for conn?

File: src/server/models/Reading.js [hunk 6]
```diff
@@ -26,85 +25,95 @@ class Reading {
 	 * Returns a promise to create the readings table.
 	 * @return {Promise.<>}
 	 */
-	static createTable() {
-		return getDB().none(sqlFile('reading/create_readings_table.sql'));
+	static createTable(conn) {
```
Comment (huss) [inline src/server/models/Reading.js:30]: @param for conn for following ones?

File: src/server/models/User.js [hunk 7]
```diff
@@ -21,60 +20,66 @@ class User {
...
 	}
 
 	/**
 	 * Returns a promise to update a user's password
+	 * @param conn is the connection to use.
 	 * @returns {Promise.<array.<User>>}
 	 */
-	static async updateUserPassword(email, passwordHash) {
-		return getDB().none(sqlFile('user/update_user_password.sql'), { email: email, password_hash: passwordHash });
+	static async updateUserPassword(conn, email, passwordHash) {
```
Comment (huss) [inline src/server/models/User.js]: I noticed conn is the first param here but last in other cases.

File: src/server/routes/users.js [hunk 8]
```diff
@@ -40,6 +42,7 @@ router.get('/:user_id', async (req, res) => {
 	if (!validate(req.params, validParams).valid) {
 		res.sendStatus(400);
 	} else {
+		const conn = getConnection();
```
Comment (huss) [inline src/server/routes/users.js:45]: I'm uncertain where this conn is used.

File: src/server/test/db/compressedReadingsTests.js [hunk 9]
```diff
@@ -50,40 +44,40 @@ mocha.describe('Compressed Readings', () => {
...
 		const expectedSecondCompressedRate = reading3.reading;
-		chai.expect(compressedReadings[meter.id][1].reading_rate).to.be.closeTo(expectedSecondCompressedRate, 0.0001);
+		expect(compressedReadings[meter.id][1].reading_rate).to.be.closeTo(expectedSecondCompressedRate, 0.0001);
 	});
 
 	mocha.it('compresses readings that overlap an end point', async () => {
 		const reading1 = new Reading(meter.id, 100, timestamp1, timestamp2);
 		const reading2 = new Reading(meter.id, 200, timestamp2, timestamp3);
-		await Reading.insertAll([reading1, reading2]);
+		await Reading.insertAll([reading1, reading2], conn);
```
Comment (huss) [inline src/server/test/db/compressedReadingsTests.js:63]: I don't know the logic but want to be sure conn is properly set in this code and next.

File: src/server/test/db/loadFromCsvStreamTests.js [hunk 10]
```diff
@@ -90,10 +90,12 @@ mocha.describe('Read mamc log from a file: ', () => {
 				const endTimestamp = moment(row[1], 'MM/DD/YYYY HH:mm');
 				const startTimestamp = moment(row[1], 'MM/DD/YYYY HH:mm').subtract(60, 'minutes');
 				return new Reading(meter.id, readRate, startTimestamp, endTimestamp);
-			}, (readings, tx) => Reading.insertOrIgnoreAll(readings, tx));
+			}, (readings, tx) => Reading.insertOrIgnoreAll(readings, tx),
+			conn
```
Comment (huss) [inline src/server/test/db/loadFromCsvStreamTests.js:94]: Again, I'm no expert on this logic but want to check conn is set here and below.

**Review by huss — APPROVED** [review]
I tried to look this over for obvious concerns. Only a few comments. I'm taking the unusual step of approving so we can move forward with 0.5. However, I still want someone else to carefully go through these changes before we go into production.

**Review by huss — APPROVED** [review]
Seems fine.

File: src/server/log.js [hunk 11]
```diff
@@ -48,24 +49,36 @@ class Logger {
...
+		}
 
-					// So we just try to convert whatever we got to a string and include it. It's better
-					// than nothing.
-					messageToLog += `An error was included, but it was not an Error object:\n${error}`;
+		// Always log to the logfile.
+		if (this.logToFile) {
+			fs.appendFile(logFile, messageToLog, err => {
+				if (err) {
+					console.error(`Failed to write to log file: ${err}`); // tslint:disable-line no-console
```
Comment (kuchtact) [inline src/server/log.js]: Do we want to also write out the stack trace just like in line 102 of this file?

File: src/server/log.js [hunk 12]
```diff
@@ -141,9 +147,17 @@ class Logger {
 
 }
 
-
 const defaultLogger = new Logger(logFile);
 
+/*
+ * Wherever logging is available, the process should log unhandled rejections.
```
Comment (kuchtact) [inline src/server/log.js]: Maybe add a comment on what exactly the 'process' is. I'm not sure when looking at `process.on(...` what exactly `process` is. I'm sure it is something obvious a little more on what exactly that is (whether it be something we are importing or something else) might be useful.

File: src/server/migrations/migrateDatabase.js [hunk 13]
```diff
@@ -169,13 +169,17 @@ async function migrateDatabaseTransaction(neededFiles, allMigrationFiles) {
...
  * @param toVersion is the version wanting to migrate to
  * @param migrationItems is the list of migration that users register
+ * @param conn is the connection to use.
  */
-async function migrateAll(toVersion, migrationItems) {
-	const currentVersion = await Migration.getCurrentVersion();
+async function migrateAll(toVersion, migrationItems, conn) {
+	const currentVersion = await Migration.getCurrentVersion(conn);
+	if (compareSemanticVersion(currentVersion, toVersion) === 0) {
+		throw new Error('You have the highest version');
```
Comment (kuchtact) [inline src/server/migrations/migrateDatabase.js:168]: Do we not want people to be able to roll back?

File: src/server/models/Baseline.js [hunk 14]
```diff
@@ -14,15 +13,15 @@ class Baseline {
 		this.baselineValue = baselineValue;
 		this.note = note;
 	}
-	static createTable() {
-		return getDB().none(sqlFile('baseline/create_baseline_table.sql'));
+	static createTable(conn) {
```
Comment (kuchtact) [inline src/server/models/Baseline.js:16]: Maybe add block comments to each of these methods. They will probably be a bit redundant but it will keep with the code style of the other `*.js` files.

File: src/server/models/Group.js [hunk 15]
```diff
@@ -176,28 +176,28 @@ class Group {
...
+	async getParents(conn) {
+		const rows = await conn.any(sqlFile('group/get_parents_by_group_id.sql'), { child_id: this.id });
 		return rows.map(row => row.parent_id);
 	}
 
 	/**
 	 * Returns a promise to delete a group and purge all trace of it form the memories of its parents and children
 	 * @param groupID The ID of the group to be deleted
-	 * @param conn The connection to be used. Defaults to (*GASP!*) the default database connection
+	 * @param conn the connection to be used.
```
Comment (kuchtact) [inline src/server/models/Group.js:196]: I really think that the `(*GASP!*)` part of the previous comment needs to stay.

File: src/server/models/Migration.js [hunk 16]
```diff
@@ -25,50 +24,53 @@ class Migration {
...
-	static async createTable() {
-		await getDB().none(sqlFile('migration/create_migration_table.sql'));
-		await Migration.insertDefaultMigration();
+	static async createTable(conn) {
+		await conn.none(sqlFile('migration/create_migration_table.sql'));
+		await Migration.insertDefaultMigration(conn);
 	}
 
-	static async insertDefaultMigration() {
+	static async insertDefaultMigration(conn) {
```
Comment (kuchtact) [inline src/server/models/Migration.js:35]: Block comment goes here.

File: src/server/models/Migration.js [hunk 17]
```diff
@@ -25,50 +24,53 @@ class Migration {
 
 	/**
 	 * Returns a promise to create the migration table.
+	 * @param conn is the connection to use.
```
Comment (kuchtact) [inline src/server/models/Migration.js:27]: Should we keep the copy paste on the `@param conn the connection to be used.` instead of this?

File: src/server/models/Preferences.js [hunk 18]
```diff
@@ -24,28 +23,37 @@ class Preferences {
...
+	 */
+	static async get(conn) {
+		const row = await conn.one(sqlFile('preferences/get_preferences.sql'));
 		return Preferences.mapRow(row);
 	}
 
-	static async update(newPreferences) {
+	/**
+	 * Update the preferences in the database.
+	 * @param conn the database connection to use.
```
Comment (kuchtact) [inline src/server/models/Preferences.js:51]: I like how line 42 and this line have different comments for `@param conn`. We could also see how many different ways we could describe what `conn` is. Hmmmm...

File: src/server/models/Reading.js [hunk 19]
```diff
@@ -24,87 +23,109 @@ class Reading {
...
 		return new Reading(row.meter_id, row.reading, row.start_timestamp, row.end_timestamp);
 	}
 
+	/**
+	 * Returns the number of readings which exist in the database, total.
+	 * @param conn the connection to use
+	 * @returns {number} the number of readings in the entire readings table
+	 */
+	static async count(conn) {
+		const { count } = await conn.one('SELECT COUNT(*) as count FROM readings');
```
Comment (kuchtact) [inline src/server/models/Reading.js:108]: Do we want to have sql stuff actually written in the `.js` file? I know it's a real simple query but to keep with how all the other queries are set up, it might be better to have this as a `.sql` file instead.

File: src/server/models/Reading.js [hunk 20]
```diff
@@ -24,87 +23,109 @@ class Reading {
...
 	 * Returns a promise to insert or update all of the given readings into the database (as a transaction)
 	 * @param {array<Reading>} readings the readings to insert or update
-	 * @param conn the connection to use. Defaults to the default database connection.
+	 * @param conn is the connection to use.
 	 * @returns {Promise.<>}
 	 */
-	static insertOrUpdateAll(readings, conn = getDB) {
-		return conn().tx(t => t.sequence(function seq(i) {
+	static insertOrUpdateAll(readings, conn) {
+		return conn.tx(t => t.sequence(function seq(i) {
```
Comment (kuchtact) [inline src/server/models/Reading.js:132]: Can we give `seq` name that better explains what it is? It seems like `seq` just means sequence but I'm not sure why that is the naming for what this does.

File: src/server/models/Reading.js [hunk 21]
```diff
@@ -162,11 +183,11 @@ class Reading {
...
 	 * @param {Moment?} toTimestamp An optional end point for the time range
 	 * @param numPoints The number of points to compress to. Defaults to 500
-	 * @param conn the connection to use. Defaults to the default database connection.
+	 * @param conn is the connection to use.
 	 * @return {Promise<object<int, array<{reading_rate: number, start_timestamp: Date, end_timestamp: Date}>>>}
 	 */
-	static async getCompressedReadings(meterIDs, fromTimestamp = null, toTimestamp = null, numPoints = 500, conn = getDB) {
-		const allCompressedReadings = await conn().func('compressed_readings',
+	static async getCompressedReadings(meterIDs, fromTimestamp = null, toTimestamp = null, numPoints = 500, conn) {
+		const allCompressedReadings = await conn.func('compressed_readings',
```
Comment (kuchtact) [inline src/server/models/Reading.js:220]: Why does this use `func` instead of doing an sql file call. I'm fine with how it is, maybe just a comment to explain why it is different.

File: src/server/routes/baseline.js [hunk 22]
```diff
@@ -2,29 +2,32 @@
...
+		const baseline = new Baseline(
 			req.body.meterID,
 			req.body.applyStart,
 			req.body.applyEnd,
 			req.body.calcStart,
 			req.body.calcEnd,
-			req.body.note
-		);
-		await baseline.insert();
+			req.body.note);
```
Comment (kuchtact) [inline src/server/routes/baseline.js:29]: I'm not sure if I like having `);` at the end of a line instead of on a new line. The nice thing about having it on a new line is that it makes it real easy to see all the params entering `Baseline`.

File: src/server/routes/readings.js [hunk 23]
```diff
@@ -52,14 +53,15 @@ router.get('/line/meters/:meter_ids', async (req, res) => {
...
+	if (!validate(req.params, validParams).valid || !validate(req.query, validQueries).valid) {
 		res.sendStatus(400);
 	} else {
+		const conn = getConnection();
 		// We can't do .map(parseInt) here because map would give parseInt a radix value of the current array position.
 		const meterIDs = req.params.meter_ids.split(',').map(s => parseInt(s));
 		const timeInterval = TimeInterval.fromString(req.query.timeInterval);
 		try {
-			const rawCompressedReadings = await Reading.getCompressedReadings(meterIDs, timeInterval.startTimestamp, timeInterval.endTimestamp, 100);
+			const rawCompressedReadings = await Reading.getCompressedReadings(meterIDs, timeInterval.startTimestamp, timeInterval.endTimestamp, 100, conn);
```
Comment (kuchtact) [inline src/server/routes/readings.js:64]: Should we make the function then params into two lines just like on line 110?

File: src/server/routes/readings.js [hunk 24]
```diff
@@ -193,16 +198,18 @@ router.get('/bar/groups/:group_ids', async (req, res) => {
 			}
 		}
 	};
-	if (!validate(req.params, validParams).valid || !validate(validQueries, req.query).valid) {
+
```
Comment (kuchtact) [inline src/server/routes/readings.js:201]: Do we want this extra line? The other places where a new validation if statement is do not have the extra space.

File: src/server/routes/users.js (hunk 8 above)
Comment (kuchtact) [reply src/server/routes/users.js:45]: It is used on line 47.

File: src/server/services/addMamacMeters.js [hunk 25]
```diff
@@ -5,15 +5,28 @@
...
+		log.error(`Expected one argument (path to csv file of meter ips), but got ${args.length} instead`, 'error');
+	} else {
+		const absolutePath = path.resolve(args[0]);
+		log.info(`Importing meters from ${absolutePath}`);
+		const conn = getConnection();
+		try {
+			const errors = await insertMetersWrapper(absolutePath, conn);
+		} catch (errors) {
+			for (const err of errors) {
+				log.error(`Error inserting meters: ${err}`, err);
```
Comment (kuchtact) [inline src/server/services/addMamacMeters.js:24]: Should we also add stack traces? Maybe just once since they are all similar? I'm not sure.

File: src/server/test/common.js [hunk 26]
```diff
@@ -0,0 +1,92 @@
...
+const testUser = new User(undefined, 'test@example.invalid', bcrypt.hashSync('password', 10));
+testUser.password = 'password';
+
+async function recreateDB() {
+	conn = testDB.getConnection();
+	// This should drop all database objects, as long as they were all created by the current database user
+	// They should be, since they were all created during a previous test.
+	await conn.none('DROP OWNED BY current_user;');
+	await createSchema(conn);
+	await testUser.insert(conn);
```
Comment (kuchtact) [inline src/server/test/common.js:69]: Add a comment to what `testUser.insert(conn)` does since it is not immediately obvious to me.

File: src/server/test/db/barchartReadingsTests.js [hunk 27]
```diff
@@ -26,18 +16,23 @@ mocha.describe('Barchart Readings', () => {
...
 		const reading3 = new Reading(meter.id, 300, timestamp3, timestamp4);
 		const reading4 = new Reading(meter.id, 400, timestamp4, timestamp5);
-		await Reading.insertAll([reading1, reading2, reading3, reading4]);
+		await Reading.insertAll([reading1, reading2, reading3, reading4], conn);
 
-		const barchartReadings = await Reading.getBarchartReadings([meter.id], moment.duration(2, 'h'));
+		// TODO: This is awkward. Is there a better way to have conn as a non-optional
+		// without requiring changing EVERY call to getBarchartReadings?
+		// If not, well, we need to change every call.
+		const barchartReadings = await Reading.getBarchartReadings([meter.id], moment.duration(2, 'h'), null, null, conn);
```
Comment (kuchtact) [inline src/server/test/db/barchartReadingsTests.js:35]: I think it is just fine to change all of these calls because then it is easy to see where exactly `conn` is used.

File: src/server/test/db/compressedReadingsTests.js [hunk 28]
```diff
@@ -103,39 +101,40 @@ mocha.describe('Compressed Readings', () => {
...
-			await groupB.adoptMeter(meter2.id);
-			await groupC.adoptGroup(groupA.id);
-			await groupC.adoptGroup(groupB.id);
-
-			// Add some readings to the meters
+			await groupA.adoptMeter(meter.id, conn);
+			await groupB.adoptMeter(meter2.id, conn);
+			await groupC.adoptGroup(groupA.id, conn);
+			await groupC.adoptGroup(groupB.id, conn);
 			const reading1 = new Reading(meter.id, readingValue, startTimestamp, endTimestamp);
```
Comment (kuchtact) [inline src/server/test/db/compressedReadingsTests.js:121]: I think there should be a bit of spacing between adding the meters and then adding the readings. Makes for easier... reading.

File: src/server/test/db/groupTests.js [hunk 29]
```diff
@@ -4,98 +4,96 @@
...
+		const groupPostInsert = await Group.getByName(groupPreInsert.name, conn);
 		expect(groupPostInsert).to.have.property('name', groupPreInsert.name);
 		expect(groupPostInsert).to.have.property('id', groupPreInsert.id);
 	});
 	mocha.it('can be renamed', async () => {
+		conn = testDB.getConnection();
 		let larry = new Group(undefined, 'Larry');
-		await larry.insert();
+		await larry.insert(conn);
 		// pull larry back out of the db so that we get his ID
```
Comment (kuchtact) [inline src/server/test/db/groupTests.js:35]: Capitalization on `p` in `Pull`. Does `larry` also need to be capitalized?

File: src/server/test/db/groupTests.js [hunk 30]
```diff
@@ -104,87 +102,90 @@ mocha.describe('Groups', () => {
 		});
 
 		mocha.it('can disown child groups', async () => {
-			const parent = await Group.getByName('A');
-			const lovedChild = await Group.getByName('B');
-			const impendingOrphan = await Group.getByName('C');
+			conn = testDB.getConnection();
+			const parent = await Group.getByName('A', conn);
+			const lovedChild = await Group.getByName('B', conn);
+			const impendingOrphan = await Group.getByName('C', conn);
```
Comment (kuchtact) [inline src/server/test/db/groupTests.js:108]: ... these variable names ...

File: src/server/test/db/insertMamacReadingsFromCSVTests.js [hunk 31]
```diff
@@ -4,56 +4,52 @@
...
-const mocha = require('mocha');
-
 mocha.describe('Insert Mamac readings from a file', () => {
-	mocha.beforeEach(recreateDB);
 	let meter;
 	mocha.beforeEach(async () => {
-		await new Meter(undefined, 'Meter', null, false, Meter.type.MAMAC).insert();
-		meter = await Meter.getByName('Meter');
+		conn = testDB.getConnection();
+		await new Meter(undefined, 'Meter', null, false, Meter.type.MAMAC).insert(conn);
```
Comment (kuchtact) [inline src/server/test/db/insertMamacReadingsFromCSVTests.js]: When similar code in `compressedReadingsTests.js` was in a transaction. Do we want this as a transaction or not?

File: src/server/test/db/insertMamacReadingsFromCSVTests.js [hunk 32]
```diff
@@ -4,56 +4,52 @@
...
 		const testFilePath = path.join(__dirname, 'data', 'test-readings-invalid.csv');
 		const readingDuration = moment.duration(1, 'hours');
 
 		try {
-			await loadMamacReadingsFromCsvFile(testFilePath, meter, readingDuration);
+			await loadMamacReadingsFromCsvFile(testFilePath, meter, readingDuration, conn);
 			expect.fail('should have thrown an exception');
 		} catch (e) {
 			// We want this to error
+			// TODO: I think Mocha actually has a way to do this with expect()
```
Comment (kuchtact) [inline src/server/test/db/insertMamacReadingsFromCSVTests.js]: Did we find a way to do this?

File: src/server/test/db/metasysTests.js [hunk 33]
```diff
@@ -0,0 +1,74 @@
...
+const Meter = require('../../models/Meter');
+const Reading = require('../../models/Reading');
+const readMetasysData = require('../../services/readMetasysData');
+
+mocha.describe('Metasys readings', () => {
+	mocha.describe('with metasys-duplicate meter', () => {
+		mocha.beforeEach(async () => {
+			conn = testDB.getConnection();
+			await new Meter(undefined, 'metasys-duplicate', null, false, Meter.type.METASYS).insert(conn);
+		//	meter = await Meter.getByName('metasys-duplicate');
```
Comment (kuchtact) [inline src/server/test/db/metasysTests.js]: Why is this commented out?

File: src/server/test/db/metasysTests.js [hunk 34]
```diff
@@ -0,0 +1,74 @@
...
+	mocha.describe('with metasys-invalid meter', () => {
+		mocha.beforeEach(async () => {
+			conn = testDB.getConnection();
+			await new Meter(undefined, 'metasys-invalid', null, false, Meter.type.METASYS).insert(conn);
+		});
+
+		mocha.it('errors correctly on an invalid file', () => {
+			conn = testDB.getConnection();
+			const testFilePath = path.join(__dirname, 'data', 'metasys-invalid.csv');
+			return expect(readMetasysData(testFilePath, 30, 1, false, conn)).to.eventually.be.rejected;
```
Comment (kuchtact) [inline src/server/test/db/metasysTests.js:44]: Why does this expect `return` instead of `await`?

File: src/server/test/db/migrations.js [hunk 35]
```diff
@@ -84,41 +75,46 @@ mocha.describe('Migrations', () => {
 			};
 			migrationList.push(item);
 		}
-		mocha.beforeEach(recreateDB);
 		mocha.beforeEach(async () => {
-			await clearMigrationsTable();
+			const conn = testDB.getConnection();
+			await clearMigrationsTable(conn);
 			//await new Migration(undefined, '0.0.0', '0.100.0');
```
Comment (kuchtact) [inline src/server/test/db/migrations.js]: Why is this commented out?

File: src/server/test/migration/migrateDatabaseInvalidTests.js [hunk 36]
```diff
@@ -0,0 +1,60 @@
...
+
+// This mocks registerMigration.js
+for (let i = 0; i < versionLists.length; i++) {
+	const fromVersion = versionLists[i].split('-')[0];
+	const toVersion = versionLists[i].split('-')[1];
+	const item = {
+		fromVersion,
+		toVersion,
+		up: async dbt => {
+			// migration here
```
Comment (kuchtact) [inline src/server/test/migration/migrateDatabaseInvalidTests.js:23]: What does `migration here` mean?

**Review by kuchtact — CHANGES_REQUESTED** [review]
Pretty good overall. A couple possible changes to make but nothing major.

File: src/server/test/db/barchartReadingsTests.js (hunk 27 above)
Comment (NoraCodes) [reply src/server/test/db/barchartReadingsTests.js:35]: What I meant here was to eliminate the `null, null` near the end.

Comment (kuchtact) [reply src/server/test/db/barchartReadingsTests.js:35]: Sounds good. I can tell you I have absolutely zero clue how to do that.

**Comment by huss** [comment]
I think this is where we are posting comments on the big merge for 0.5.

I've only done limited testing on the server but here are some items I have noticed:

- When you use compare you often get "Select one or more items to compare". At other times it does not display all the meters/groups but only does one. It also does not display items if you go from line or bar to compare. I cannot get any group to display in compare.

- If you try to use a chart link, the dashboard pops up for a fraction of a second and then goes away. You are now at the main URL for the site.

- (not a bug and not new but noting) If you try to use a select all in the chart link it selects many items on the dashboard. Given the length, it would be nice to only get the link. Given the layout this might be tricky (I don't know) so not a priority, esp. if difficult.

- If you go to the new groups page and try to make a change it correctly asks for a login. The meters page puts a message on the side about a failure (not told why). In the long-term we should be consistent. If not hard, maybe we should hide the buttons/features you cannot do if not logged in (we should discuss)

- I tried to edit on meters to test. The save acted weird and now I cannot see any meters. I closed/opened the page and it came back/worked. I'm not sure what caused it but something seems off. Finally, I unsure what disable meter does since it did not change the meters displayed.

- Have we tested HTTPS? I know some other changes are needed with the code. At this point it does not work on the server.

**Comment by NoraCodes** [comment]
> When you use compare you often get "Select one or more items to compare". At other times it does not display all the meters/groups but only does one. It also does not display items if you go from line or bar to compare. I cannot get any group to display in compare.

I think this is a known bug with compare. If not, I'm not sure what caused it, as I didn't change any front-end code from the compare with shift PR.

> If you try to use a chart link, the dashboard pops up for a fraction of a second and then goes away. You are now at the main URL for the site.

This is definitely a bug, I'll do my best to squash it tonight.

> I tried to edit on meters to test. The save acted weird and now I cannot see any meters. I closed/opened the page and it came back/worked. I'm not sure what caused it but something seems off.

I'll try to reproduce this on my machine, I currently can't but have some theories.

> Finally, I unsure what disable meter does since it did not change the meters displayed.

Disabled meters are not updated when `updateMamacMeters` is run. This terminology is from the pre-meters-editing database but could probably be made more clear.

> Have we tested HTTPS? I know some other changes are needed with the code. At this point it does not work on the server.

As I've mentioned before, we can't enable HTTPS through just code changes; it needs a reworking of how the web server (Apache) presents our sites, and development (3030) currently does not have a subdirectory associated with it.

> If you go to the new groups page and try to make a change it correctly asks for a login. The meters page puts a message on the side about a failure (not told why). In the long-term we should be consistent. If not hard, maybe we should hide the buttons/features you cannot do if not logged in (we should discuss)

This is happening because you have an existing token which has timed out. This is a bug but will not happen for people who have never been logged in; the buttons are hidden for them.

Many thanks!

File: src/server/migrations/migrateDatabase.js (hunk 13 above)
Comment (NoraCodes) [reply src/server/migrations/migrateDatabase.js:168]: This is not possible as we don't have a mechanism for down migrations. Eventually we definitely need to change that.

File: src/server/test/db/metasysTests.js (hunk 34 above)
Comment (NoraCodes) [reply src/server/test/db/metasysTests.js:44]: We get better error messages by giving the promise back to Mocha here.

File: src/server/log.js [hunk 37]
```diff
@@ -119,7 +119,7 @@ class Logger {
 	 * Log the given message at the INFO level
 	 * @param {String} message the message to log
 	 * @param {Error?} error An optional error object to include information about
-	 * @param {boolean?} skipMail Don't e-mail this message even if we would normally emit an e-mail for this level.
+	 * @param {boolean?} skipMail Don't e-mail this message eveBland error messagen if we would normally emit an e-mail for this level.
```
Comment (kuchtact) [inline src/server/log.js]: What happened here. This comment went wacko.

**Review by kuchtact — APPROVED** [review]

File: src/server/log.js (hunk 37 above)
Comment (NoraCodes) [reply src/server/log.js]: Oh dear. I must have accidentally hit paste.

**Review by huss — APPROVED** [review]
Seems fine.

**Review by huss — APPROVED** [review]
Fine. Just for the record, this fixes errors logged during the changeover.
