### PR TITLE
might have fixed the plotly issue?

### LINKED ISSUE #587: small change plotly graphic usage
Relates to LineChartContainer.ts in src/client/app/containers. https://plot.ly/javascript/hover-text-and-formatting/ has info. Seems to use line (and marker) color and wonder if we should use line since no markers seen as in:
line: {
	shape: 'spline',
	width: 3,
	color: getGraphColor(label)
},
// marker: {color: getGraphColor(label)}

### PR DESCRIPTION
**Pull request by miriammjr**
# Description

Uses line instead of marker for the hovering in charts. 

Fixes #587 

## Type of change

(Check the ones that apply by placing an "x" instead of the space in the [ ] so it becomes [x])

- [ ] Note merging this changes the node modules
- [ ] Note merging this changes the database configuration.
- [ ] This change requires a documentation update

## Checklist

(Note what you have done by placing an "x" instead of the space in the [ ] so it becomes [x]. It is hoped you do all of them.)

- [x] I have followed the [OED pull request](https://openenergydashboard.github.io/developer/pr.html) ideas
- [x] I have removed text in ( ) from the issue request

### CODE REVIEW

**Comment by huss** [comment]
The checks failed due to linting issues. Hopefully it will pass after fixing them. These should be addressed before the PR will be reviewed.

File: src/client/app/containers/BarChartContainer.ts [hunk 1]
```diff
@@ -53,7 +53,11 @@ function mapStateToProps(state: State) {
 					text: hoverText,
 					hoverinfo: 'text',
 					type: 'bar',
-					marker: {color: getGraphColor(colorID, DataType.Meter)}
+					line: {
```
Comment (huss) [inline src/client/app/containers/BarChartContainer.ts]: Since this is a bar graphic, I'm not certain we should be using the line attribute. Was there a specific reason to do this? Note the color of the bars differs from the same item on the line graphic. I don't think it used to do that.

Applies below as well.

**Review by huss — CHANGES_REQUESTED** [review]
Does what was expected and seems to work fine. Just one comment on bar graphics to think about.

File: src/client/app/containers/BarChartContainer.ts (hunk 1 above)
Comment (huss) [reply src/client/app/containers/BarChartContainer.ts]: fixed

**Review by huss — APPROVED** [review]
