### PR TITLE
Fix: Refresh now properly refetches Units to show suffix conversions

### LINKED ISSUE #1446: Redux update failure on suffix unit conversion creation
### Describe the bug

After a suffix unit is created:

Image

Once can create a conversion with it (normally the source):

Image

The conversion page then shows the destination of the OED created units as undefined:

Image

If the Redux state is examined, it shows the new units are not present. I seems they are not fetched and this needs to be added as an invalidated tag to the Redux Toolkit action on saving a new conversion with a suffix.

### To Reproduce

See above.

### Expected behavior

It should properly show the new units.

### Additional context

None

### PR DESCRIPTION
**Pull request by shaikhibrahim2000**
# Description

This PR adds 'Units' to the invalidatesTags array in the refresh mutation. This ensures that units are automatically refetched after backend refresh, solving the issue where suffix conversions were not appearing until a manual reload.

Fixes #1446 

## Type of change

(Check the ones that apply by placing an "x" instead of the space in the [ ] so it becomes [x])

- [ ] Note merging this changes the database configuration.
- [ ] This change requires a documentation update

## Checklist

(Note what you have done by placing an "x" instead of the space in the [ ] so it becomes [x]. It is hoped you do all of them.)

- [x] I have followed the [OED pull request](https://openenergydashboard.org/developer/pr/) ideas
- [x] I have removed text in ( ) from the issue request
- [x] You acknowledge that every person contributing to this work has signed the [OED Contributing License Agreement](https://openenergydashboard.org/developer/cla/) and each author is listed in the Description section.

## Limitations

(Describe any issues that remain or work that should still be done.)

### CODE REVIEW

File: src/client/app/components/unit/UnitsDetailComponent.tsx [hunk 1]
```diff
@@ -15,6 +15,7 @@ import CreateUnitModalComponent from './CreateUnitModalComponent';
 import UnitViewComponent from './UnitViewComponent';
 import { titleStyle, tooltipBaseStyle } from '../../styles/modalStyle';
```
Comment (huss) [inline src/client/app/components/unit/UnitsDetailComponent.tsx]: Please remove extra line added.

File: src/client/app/components/unit/UnitsDetailComponent.tsx [hunk 2]
```diff
@@ -27,7 +28,6 @@ export default function UnitsDetailComponent() {
 	const unitData = useAppSelector(selectAllUnits);
 
 	const isRefreshingReadings = useAppSelector(selectRefreshingReadings);
-
 	return (
```
Comment (huss) [inline src/client/app/components/unit/UnitsDetailComponent.tsx]: Please put back the blank line.

File: src/client/app/redux/slices/appStateSlice.ts [hunk 3]
```diff
@@ -63,6 +63,7 @@ export const appStateSlice = createThunkSlice({
 		setRefresingReadings: create.reducer<boolean>((state, action) => {
 			state.refreshingReadings = action.payload;
 		}),
+
 		initApp: create.asyncThunk(
```
Comment (huss) [inline src/client/app/redux/slices/appStateSlice.ts]: Please remove extra line added, esp. since only change in this file.

**Review by huss — CHANGES_REQUESTED** [review]
Thanks to @shaikhibrahim2000 for another contribution. I have made a few comments on blank lines add/removed that should be addressed. I think the first time I tested this it failed but I have not been able to reproduce so I'm hoping it was a fluke or something I did that was wrong. I'm noting in case someone else sees this.

**Comment by huss** [comment]
@shaikhibrahim2000 I wanted to check to see the status of addressing the comments. Please let me know if you need something.

**Comment by huss** [comment]
@shaikhibrahim2000  It has been over a month since I last checked on the status without reply. OED appreciates your work so far. OED would like to move this work forward. If you are working on this or need help then please leave a comment. If nothing is posted by 1 Aug. then OED will move forward to complete this work.

**Comment by shaikhibrahim2000** [comment]
@huss, Please let me know if the formatting works. Thanks

**Review by huss — APPROVED** [review]
Thanks to @shaikhibrahim2000 for addressing the comments. Testing and review found no issues so this is ready to merge. Congratulation.
