### PR TITLE
Redux Toolkit Migration

### LINKED ISSUE #817: routecomponent's authentication functions do not work as expected
### Describe the bug

Due to how asynchronous functions are handled, the current method in which checkAuth, requireAuth, and requireRole are written has a fundamental issue. The token validation is an asynchronous function, but the functions themselves must return a value synchronously. This means a value is returned before the async block is finished. because of this, users are directed to the page they try to access regardless of the token authentication. This is the root cause of issue #816, although I have found a workaround for that issue.

Currently, apart from #816, this is a silent issue. Some error is encountered during the process which causes the token to be removed and then the function to be re-run, which will properly redirect the user (see screenshots). For now, this works as intended. Users are able to access a page only if they have access, and invalid tokens are deleted and then the user is redirected. The problem is that the code only works because of further errors popping up downstream.

For example, consider requireAuth:
```typescript
public requireAuth(component: JSX.Element) {
// Redirect route to home page if the auth token does not exist
if (!hasToken() || !this.props.loggedInAsAdmin) {
	return <Redirect to='/' />;
}
// Verify that the auth token is valid.
// Needs to be async because of the network request
(async () => {
	if (!(await verificationApi.checkTokenValid())) {
		showErrorNotification(translate('invalid.token.login.admin'));
		// We should delete the token when we know that it is expired. Ensures that we don't not leave any unwanted tokens around.
		deleteToken();
		// This ensures that if there is no token then there is no stale profile in the redux store.
		this.props.clearCurrentUser();
		// Route to login page since the auth token is not valid
		return <Redirect to='/' />;
	}
	return component;
})();
return component;
}
```

When the function is evaluated, if the user has a token, the last return statement is immediately returned. Only after the await function finishes does the rest of the code evaluate. This means that the function may attempt to return a redirect, but this second return value is never processed.

### To Reproduce

1. Log in as an admin user
2. Wait for the token to become invalid
3. Access an admin page
4. Inspect the web console

### Expected behavior

There should be no improper API calls nor other react errors.

### Screenshots

image

### PR DESCRIPTION
**Pull request by ChrisMart21**
# Description

This pull request primarily focuses on updating the project to modern Redux patterns by migrating to the recommended '[Redux-Toolkit](https://redux-toolkit.js.org/)' while addressing several other minor issues along the way.

Fixes:
- #817 
  - Reworked the snippets in question to use react-routerv6's outlets + redux state.
- #92 
  - Data Fetching now managed via RTK Query. Fetching/caching simplified and more robust.
- #886 
  - Preferences removed the container, and added hooks + selectors
- #893 
  - All components now are functional. Dropped the container+component HOC pattern.
- #466 
  - Graphs now scale / are responsive 

Partially addresses 

- #726 / #888 
  -  Continues the ongoing push towards functional components.
  - All graph types other than compare
  - main containers
  - admin preferences/userpages
  
- #1093 
  - Continue ongoing switch towards notifications. 

## Type of change

- [ ] Note merging this changes the database configuration.
- [x] This change requires a documentation update

## Checklist

- [x] I have followed the [OED pull request](https://openenergydashboard.github.io/developer/pr.html) ideas
- [x] I have removed text in ( ) from the issue request
- [x] You acknowledge that every person contributing to this work has signed the [OED Contributing License Agreement](https://openenergydashboard.github.io/developer/cla.html) and each author is listed in the Description section.

## Limitations
- This pull request introduces numerous changes across the front end that are yet to be thoroughly tested. While not entirely feature-complete, it represents a significant step towards migrating to RTK. A thorough evaluation is necessary to ensure these changes have not impaired the functionality of the app.
  - Close evaluation and iterations have been ongoing since initial posting of PR. It is reaching its final stages, and is believed to be stable. Further testing and evaluation from the community is always welcome, and encouraged.

- This PR has a version bump to react-router-v6. This change introduces several newer hooks that pair well with the ongoing migration towards functional components. This did however introduce some backwards compatibility issues with the current implementation of the unsaved warning. This component has to be reworked for compatibility with react-router-v6, but also Redux RTK.

 - There was issues/difficulty migrating the entirety of 'Maps'. Maps currently is still using legacy redux and either needs to be reworked, or migrated properly by someone more knowledgeable on this section of the code base.
   - While maps utilizes some newer RTK elements, it is still heavily reliant on legacy redux patterns.  
   - Further work is necessary on this section of the migration.

- Redux-Toolkit introduces some new devmode checks which conflict with some of the legacy Redux code. For example, the 'serializableCheck' has to currently be suppressed due to the use of TimeInverval in Redux State. TimeInterval is a class which is non-serialiazable which needs to be addressed. Additionally 'immutableCheck' is also currently has conflicts with the maps implementation. For the time being, these checks are disabled to prevent the app from malfunctioning, however the goal is to address these issues, and have all dev mode checks enabled. 
  - Progress has been made on this front and will likely be resolved in tandem with the Maps rework.

### CODE REVIEW

File: src/client/app/redux/api/userApi.ts [hunk 1]
```diff
@@ -0,0 +1,53 @@
...
+				url: 'api/users/delete',
+				method: 'POST',
+				body: { email }
+			}),
+			invalidatesTags: ['Users']
+		})
+	})
+})
+
+// public async editUsers(users: User[]) {
```
Comment (huss) [inline src/client/app/redux/api/userApi.ts]: Since these capabilities are above, is this commented out code needed?

File: src/client/app/redux/api/userApi.ts [hunk 2]
```diff
@@ -0,0 +1,53 @@
+/* This Source Code Form is subject to the terms of the Mozilla Public
+ * License, v. 2.0. If a copy of the MPL was not distributed with this
+ * file, You can obtain one at http://mozilla.org/MPL/2.0/. */
+
+import { NewUser, User } from '../../types/items';
+// import { authApi } from './authApi';
```
Comment (huss) [inline src/client/app/redux/api/userApi.ts]: Is auth done here?

File: src/client/app/components/admin/UsersDetailComponent.tsx [hunk 3]
```diff
@@ -2,78 +2,79 @@
...
-	const submitUnsavedChangesFunction = (successCallback: () => void, failureCallback: () => void) => {
-		// This function is called to submit the unsaved changes
-		props.submitUserEdits().then(successCallback, failureCallback);
+	const editUser = (e: React.ChangeEvent<HTMLInputElement>, targetUser: User) => {
+		// copy user, and update role
+		const updatedUser: User = { ...targetUser, role: e.target.value as UserRole }
+		// make new list from existing local user state
+		const updatedList = localUsersChanges.map(user => (user.email === targetUser.email) ? updatedUser : user)
+		setLocalUsersChanges(updatedList)
+		// editUser(user.email, target.value as UserRole);
```
Comment (huss) [inline src/client/app/components/admin/UsersDetailComponent.tsx]: I think this is done in submit so commented out code can be removed.

File: src/client/app/redux/actions/admin.ts [hunk 4]
```diff
@@ -0,0 +1,192 @@
...
+import { showErrorNotification, showSuccessNotification } from '../../utils/notifications';
+import { Dispatch, GetState, Thunk } from '../../types/redux/actions';
+import { State } from '../../types/redux/state';
+import { conversionArrayApi, preferencesApi } from '../../utils/api';
+import translate from '../../utils/translate';
+import * as moment from 'moment';
+// import { updateSelectedLanguage } from './options';
+import { graphSlice } from '../slices/graphSlice';
+import { adminSlice } from '../slices/adminSlice';
+// TODO Marked For Deletion after RTK migration solidified
```
Comment (huss) [inline src/client/app/redux/actions/admin.ts]: Still needed?

File: src/client/app/redux/actions/admin.ts [hunk 5]
```diff
@@ -0,0 +1,192 @@
...
+			dispatch2(graphSlice.actions.changeChartToRender(state.admin.defaultChartToRender));
+			if (preferences.defaultBarStacking !== state.graph.barStacking) {
+				dispatch2(graphSlice.actions.changeBarStacking());
+			}
+			if (preferences.defaultAreaNormalization !== state.graph.areaNormalization) {
+				dispatch2(graphSlice.actions.toggleAreaNormalization());
+			}
+			if (preferences.defaultLanguage !== state.options.selectedLanguage) {
+				// if the site default differs from the selected language, update the selected language and the locale
+				// dispatch2(updateSelectedLanguage(preferences.defaultLanguage));
```
Comment (huss) [inline src/client/app/redux/actions/admin.ts]: Is this now done in the component so commented out code no longer needed? Import can go if this goes.

File: src/client/app/redux/actions/admin.ts [hunk 6]
```diff
@@ -0,0 +1,192 @@
...
+/**
+ * Dispatches a fetch for admin preferences and sets the state based upon the result
+ */
+function fetchPreferences(): Thunk {
+	return async (dispatch: Dispatch, getState: GetState) => {
+		dispatch(adminSlice.actions.requestPreferences());
+		const preferences = await preferencesApi.getPreferences();
+		dispatch(adminSlice.actions.receivePreferences(preferences));
+		moment.locale(getState().admin.defaultLanguage);
+		//  TODO reference only DELETE ME
```
Comment (huss) [inline src/client/app/redux/actions/admin.ts]: Remove?

File: src/client/app/redux/actions/admin.ts [hunk 7]
```diff
@@ -0,0 +1,192 @@
...
+export function fetchPreferencesIfNeeded(): Thunk {
+	return (dispatch: Dispatch, getState: GetState) => {
+		if (shouldFetchPreferenceData(getState())) {
+			return dispatch(fetchPreferences());
+		}
+		return Promise.resolve();
+	};
+}
+
+export function submitPreferencesIfNeeded(): Thunk {
```
Comment (huss) [inline src/client/app/redux/actions/admin.ts]: I don't see where this function is used. Can you help me understand? (seems shouldSubmitPreferenceData is only used here). This may apply to other, similar functions.

File: src/client/app/components/conversion/ConversionViewComponent.tsx [hunk 8]
```diff
@@ -36,7 +37,7 @@ export default function ConversionViewComponent(props: ConversionViewComponentPr
 	const handleClose = () => {
 		setShowEditModal(false);
 	}
-
+	React.useEffect(() => undefined, [props.conversion])
```
Comment (huss) [inline src/client/app/components/conversion/ConversionViewComponent.tsx]: Could a comment be added about what this is doing? I think it updates this modal if the conversion changes.

File: src/client/app/components/conversion/ConversionsDetailComponent.tsx [hunk 9]
```diff
@@ -25,23 +20,22 @@ import { Dispatch } from 'types/redux/actions';
...
-	const conversionsState = useSelector((state: State) => state.conversions.conversions);
+	const { data: conversionsState = [], isFetching: conversionsFetching } = conversionsApi.useGetConversionsDetailsQuery();
+	// Units DataById
+	const { unitDataById = {}, isFetching: unitsFetching } = unitsApi.useGetUnitsDetailsQuery(undefined, {
+		selectFromResult: ({ data, ...result }) => ({
+			...result,
+			unitDataById: data && unitsAdapter.getSelectors().selectEntities(data)
+		})
+	})
+	// const x = useAppSelector(state => conversionsApi.endpoints.refresh.select()(state))
```
Comment (huss) [inline src/client/app/components/conversion/ConversionsDetailComponent.tsx]: status?

File: src/client/app/components/csv/MetersCSVUploadComponent.tsx [hunk 10]
```diff
@@ -37,8 +35,9 @@ export default class MetersCSVUploadComponent extends React.Component<MetersCSVU
 			window.alert(error.response.data as string);
 		}
 		// Refetch meters details.
-		store.getState().meters.hasBeenFetchedOnce = false;
-		fetchMetersDetails();
+		// Removed with rtk migration
```
Comment (huss) [inline src/client/app/components/csv/MetersCSVUploadComponent.tsx]: The meters are not being updated as desired.

File: src/client/app/components/groups/EditGroupModalComponent.tsx [hunk 11]
```diff
@@ -324,10 +324,10 @@ export default function EditGroupModalComponent(props: EditGroupModalComponentPr
 						childGroups: thisGroupState.childGroups, gps: gps, displayable: thisGroupState.displayable,
 						note: thisGroupState.note, area: thisGroupState.area, defaultGraphicUnit: thisGroupState.defaultGraphicUnit, areaUnit: thisGroupState.areaUnit
 					}
+					console.log(submitState, 'removeme')
 					// This saves group to the DB and then refreshes the window if the last group being updated and
 					// changes were made to the children. This avoid a reload on name change, etc.
-					dispatch(submitGroupEdits(submitState, (i === groupsChanged.length ? true : false) && (childMeterChanges || childGroupChanges)));
-					i++;
+					submitGroupEdits(submitState)
```
Comment (huss) [inline src/client/app/components/groups/EditGroupModalComponent.tsx]: Chris?: How does this make sure that all state is okay without reload. Also, since there is an invalidate in src/client/app/redux/api/groupsApi.ts does this do it more than needed?

Maybe look at editUnitMutation for passing parameters.

File: src/client/app/components/AppLayout.tsx [hunk 12]
```diff
@@ -0,0 +1,28 @@
...
+/**
+ * @param props Optional Children prop to render instead of using Outlet
+ * @returns The OED Application Layout. The current route as the outlet Wrapped in the header, and footer components
+ */
+export default function AppLayout(props: LayoutProps) {
+	return (
+		<>
+			<ToastContainer transition={Slide} />
+			<HeaderComponent />
+			{props.children ?? <Outlet />}
```
Comment (huss) [inline src/client/app/components/AppLayout.tsx]: Maybe comment to describe

File: src/client/app/components/MapChartComponent.tsx [hunk 13]
```diff
@@ -0,0 +1,387 @@
...
+			sizex: 500,
+			sizey: 500,
+			xanchor: 'left',
+			yanchor: 'bottom',
+			sizing: 'contain',
+			opacity: 1
+		}]
+	};
+
+	/***
```
Comment (huss) [inline src/client/app/components/MapChartComponent.tsx]: Can this be removed?

File: src/client/app/redux/api/groupsApi.ts [hunk 14]
```diff
@@ -0,0 +1,102 @@
...
+							id: childrenInfo.groupId,
+							changes: {
+								childMeters: childrenInfo.childMeters,
+								childGroups: childrenInfo.childGroups
+							}
+						}));
+						dispatch(groupsApi.util.updateQueryData('getGroups', undefined, groupDataById => { groupsAdapter.updateMany(groupDataById, updates) }))
+					}
+				} catch (e) {
+					console.log(e)
```
Comment (huss) [inline src/client/app/redux/api/groupsApi.ts]: This should be changed. log in standatd OED way and/or notify user.

File: src/client/app/components/router/GraphLinkComponent.tsx [hunk 15]
```diff
@@ -0,0 +1,113 @@
...
+					dispatchQueue.push(graphSlice.actions.updateComparePeriod({ comparePeriod: validateComparePeriod(value), currentTime: moment() }))
+					break;
+				case 'compareSortingOrder':
+					dispatchQueue.push(graphSlice.actions.changeCompareSortingOrder(validateSortingOrder(value)))
+					break;
+				case 'optionsVisibility':
+					dispatchQueue.push(appStateSlice.actions.setOptionsVisibility(value === 'true' ? true : false))
+					break;
+				case 'mapID':
+					// 'TODO, Verify Behavior & FIXME! MapLink not working as expected
```
Comment (huss) [inline src/client/app/components/router/GraphLinkComponent.tsx]: Resolve. Maybe part of map issues.

**Review by huss — COMMENTED** [review]
@ChrisMart21 This is not a formal review but some comments for us to work on as I continue to do the formal review. Many will be deleted and are informal.

File: src/client/app/redux/api/userApi.ts (hunk 1 above)
Comment (ChrisMart21) [reply src/client/app/redux/api/userApi.ts]: Was used as translation reference. This & import at the top needs to get deleted. Will mark as resolved when deleted,

File: src/client/app/redux/api/userApi.ts (hunk 2 above)
Comment (ChrisMart21) [reply src/client/app/redux/api/userApi.ts]: Auth is handled on startup, or login. If authenticated, these request headers\s will have a token for additional verification if needed. That import isn't necessary here.

File: src/client/app/components/admin/UsersDetailComponent.tsx (hunk 3 above)
Comment (ChrisMart21) [reply src/client/app/components/admin/UsersDetailComponent.tsx]: Agreed.

File: src/client/app/redux/actions/admin.ts (hunk 4 above)
Comment (ChrisMart21) [reply src/client/app/redux/actions/admin.ts]: This Entire File could be purged. 
It is not used anywhere and was used as reference for translation.

File: src/client/app/redux/actions/admin.ts (hunk 5 above)
Comment (ChrisMart21) [reply src/client/app/redux/actions/admin.ts]: This Entire File could be purged.
It is not used anywhere and was used as reference for translation.

Comment (ChrisMart21) [reply src/client/app/redux/actions/admin.ts]: I added a comment to files that need to get purged.

// TODO Marked For Deletion after RTK migration solidified

File: src/client/app/components/conversion/ConversionsDetailComponent.tsx (hunk 9 above)
Comment (ChrisMart21) [reply src/client/app/components/conversion/ConversionsDetailComponent.tsx]: refreshing now occurs as an onQueryStarted Property of the relevant mutations. Comment can be deleted.

File: src/client/app/components/groups/EditGroupModalComponent.tsx (hunk 11 above)
Comment (ChrisMart21) [reply src/client/app/components/groups/EditGroupModalComponent.tsx]: This and most other admin pages are written such that the page will reset if the cached values it relies on gets modified. In this case the groups cache is updated, therefore resets the current page/ modal. 

It seems however that this mutation is missing the onQueryStarted Logic. The window reload will be replaced with the appropriate cache invalidation(s).

File: src/client/app/components/meters/MetersDetailComponent.tsx [hunk 16]
```diff
@@ -4,129 +4,71 @@
...
-							possibleGraphicUnits={possibleGraphicUnits}
-						/>
+						<CreateMeterModalComponent />
 					</div>
 				}
-				{metersStateLoaded && unitsStateLoaded &&
+				{
 					<div className="card-container">
 						{/* Create a MeterViewComponent for each MeterData in Meters State after sorting by identifier */}
+						{/*  Optional Chaining to prevent from crashing upon startup race conditions*/}
```
Comment (huss) [inline src/client/app/components/meters/MetersDetailComponent.tsx]: Can you help me understand why this is optional chaining?

Comment (ChrisMart21) [reply src/client/app/components/meters/MetersDetailComponent.tsx]: This comment should be removed. It seems that this comment is still lingering around after some of the logic was shifted elsewhere.. This optional chaining still occurs in many of the selectors. 
One issue I was encountering during was that selectors were firing before the initial data was finished loading. This would cause fatal undefined index access issues. To prevent this I utilized optional chaining to short-circuit some of the methods. Doing this caused the methods to gracefully finish and return no data. Not sure if this is ideal, but works for now.

Similarly, the comment above no longer applies either. The sorting of meters is now handled at the store level by entity adapter. This comment should be edited . Data is no longer sorted during the render.

File: src/client/app/components/unit/EditUnitModalComponent.tsx [hunk 17]
```diff
@@ -103,15 +103,16 @@ export default function EditUnitModalComponent(props: EditUnitModalComponentProp
 	const shouldUpdateUnit = (): boolean => {
 		// true if inputted values are okay and there are changes.
 		let inputOk = true;
+		const meterDataByID = selectMeterDataById(store.getState())
```
Comment (huss) [inline src/client/app/components/unit/EditUnitModalComponent.tsx]: Curious why this one uses store directly and not useAppSelector as in somw other places.

File: src/client/app/containers/CompareChartContainer.ts [hunk 18]
```diff
@@ -180,13 +203,15 @@ function mapStateToProps(state: State, ownProps: CompareChartContainerProps): an
 			yaxis: {
 				title: unitLabel,
 				showgrid: true,
-				gridcolor: '#ddd'
+				gridcolor: '#ddd',
+				fixedrange: true
```
Comment (huss) [inline src/client/app/containers/CompareChartContainer.ts:209]: Want to check why added fixedrange?

File: src/client/app/containers/MapChartContainer.ts [hunk 19]
```diff
@@ -339,14 +349,10 @@ function mapStateToProps(state: State) {
...
-	const props: any = {
+	const props = {
 		data,
-		layout,
-		config: {
-			locales: Locales // makes locales available for use
-		}
-	};
-	props.config.locale = state.options.selectedLanguage;
+		layout
```
Comment (huss) [inline src/client/app/containers/MapChartContainer.ts:350]: I think removing the locales is why plotly is no longer using the chose language to label the axis items.

File: src/client/app/containers/CompareChartContainer.ts (hunk 18 above)
Comment (ChrisMart21) [reply src/client/app/containers/CompareChartContainer.ts:209]: I believe to avoid zooming when dragging across the graph. If this is desired behavior it can be omitted. Let me know.

File: src/client/app/components/unit/EditUnitModalComponent.tsx (hunk 17 above)
Comment (ChrisMart21) [reply src/client/app/components/unit/EditUnitModalComponent.tsx]: Good catch! This is bad practice!! It is higly advised against to import store.ts anywhere other than index. Honeslty not sure how this one made it through... Definitely needs to be addressed

File: src/client/app/components/AppLayout.tsx (hunk 12 above)
Comment (ChrisMart21) [reply src/client/app/components/AppLayout.tsx]: Sure. Done!

File: src/client/app/components/BarChartComponent.tsx [hunk 20]
```diff
@@ -0,0 +1,257 @@
...
+		if (dataset.x.length > 1) {
+			enoughData = true
+		}
+	})
+	if (datasets.length === 0) {
+		return <h1>
+			{`${translate('select.meter.group')}`}
+		</h1>
+	} else if (!enoughData) {
+		// This normal so plot.
```
Comment (huss) [inline src/client/app/components/BarChartComponent.tsx]: First, this does not seem a normal plot as it has no data. Second, I think we may want to change the translate key since not just 3D. Let me know and I can do if you want.

File: src/client/app/components/BarChartComponent.tsx [hunk 21]
```diff
@@ -0,0 +1,257 @@
...
+	} else {
+		return (
+			<Plot
+				data={datasets as Plotly.Data[]}
+				style={{ width: '100%', height: '100%' }}
+				onRelayout={handleRelayout}
+				useResizeHandler={true}
+				config={{
+					displayModeBar: false,
+					responsive: true
```
Comment (huss) [inline src/client/app/components/BarChartComponent.tsx]: locales is gone and does not seem to show language aware labels.

File: src/client/app/components/BarChartComponent.tsx [hunk 22]
```diff
@@ -0,0 +1,257 @@
...
+					bargroupgap: 0.1, // Gap between different meter's readings under the same timestamp
+					showlegend: true,
+					legend: { x: 0, y: 1.1, orientation: 'h' },
+					yaxis: {
+						title: unitLabel, showgrid: true,
+						gridcolor: '#ddd', fixedrange: true
+					},
+					xaxis: {
+						rangeslider: { visible: true },
+						// rangeselector: { visible: true },
```
Comment (huss) [inline src/client/app/components/BarChartComponent.tsx]: Needed?

File: src/client/app/components/ChartDataSelectComponentSave.tsx [hunk 23]
```diff
@@ -0,0 +1,751 @@
+// /* This Source Code Form is subject to the terms of the Mozilla Public
```
Comment (huss) [inline src/client/app/components/ChartDataSelectComponentSave.tsx]: Can this go?

File: src/client/app/components/ChartSelectComponent.tsx [hunk 24]
```diff
@@ -3,85 +3,62 @@
...
-						<FormattedMessage id='radar' />
-					</DropdownItem>
-					<DropdownItem
-						onClick={() => dispatch({ type: 'CHANGE_CHART_TO_RENDER', chartType: ChartTypes.threeD })}
-					>
-						<FormattedMessage id='3D' />
-					</DropdownItem>
+					{
+						// Make items for dropdown from enum
+						Object.values(ChartTypes)
```
Comment (huss) [inline src/client/app/components/ChartSelectComponent.tsx:45]: I like the new code but the items should be alphabetical.

File: src/client/app/containers/MapChartContainer.ts (hunk 19 above)
Comment (ChrisMart21) [reply src/client/app/containers/MapChartContainer.ts:350]: Indeed, Corrected the issue.

File: src/client/app/components/BarChartComponent.tsx (hunk 20 above)
Comment (ChrisMart21) [reply src/client/app/components/BarChartComponent.tsx]: Yes please fix the translations to whatever you find suitable. Also, yes the comment is in the wrong location.

File: src/client/app/components/BarChartComponent.tsx (hunk 21 above)
Comment (ChrisMart21) [reply src/client/app/components/BarChartComponent.tsx]: Agreed & fixed

File: src/client/app/components/BarChartComponent.tsx (hunk 22 above)
Comment (ChrisMart21) [reply src/client/app/components/BarChartComponent.tsx]: Not sure. Let me know. I'm still testing things & potential ui controls. I removed the redraw and restore, which i think should come back in some way. Similarly, I added a range slider to bar ,but not entirely sure if its here to stay. We need to solidify the UI design In the near future.

File: src/client/app/components/ChartDataSelectComponentSave.tsx (hunk 23 above)
Comment (ChrisMart21) [reply src/client/app/components/ChartDataSelectComponentSave.tsx:1]: yes! fixed

File: src/client/app/components/ChartSelectComponent.tsx (hunk 24 above)
Comment (ChrisMart21) [reply src/client/app/components/ChartSelectComponent.tsx:45]: I added a .sort() to the map method. Let me know if this works for you. Otherwise we can rollback.

File: src/client/app/components/ChartDataSelectComponentSave.tsx (hunk 23 above)
Comment (ChrisMart21) [reply src/client/app/components/ChartDataSelectComponentSave.tsx]: Yes, Fixed!

File: src/client/app/components/DateRangeComponent.tsx [hunk 25]
```diff
@@ -2,63 +2,52 @@
...
-import TooltipMarkerComponent from './TooltipMarkerComponent';
 import translate from '../utils/translate';
-import { State } from '../types/redux/state';
-import { ChartTypes } from '../types/redux/graph';
-import { Dispatch } from '../types/redux/actions';
-import { changeGraphZoomIfNeeded } from '../actions/graph';
+import TooltipMarkerComponent from './TooltipMarkerComponent';
+import { selectSelectedLanguage } from '../redux/slices/appStateSlice';
+
+// Potential Fixes, for now omitted
```
Comment (huss) [inline src/client/app/components/DateRangeComponent.tsx]: Could you explain what the fix is?

Comment (ChrisMart21) [reply src/client/app/components/DateRangeComponent.tsx]: There's an issue with the date range picker overflowing & getting overshadowed by the plotly graph when the screen size is not wide enough.

 By default the date picker does not honor the width of the parents container. Enabling this behavior with those few lines of CSS fixes this issue, but I'm not too keen on how it looks visually.

When a chart is displaying, shrink the width of the window some (with and without the css) to see what I mean.

File: src/client/app/components/ExportComponent.tsx [hunk 26]
```diff
@@ -2,213 +2,186 @@
...
-								graphExport(sortedReadings, meterIdentifier, unitLabel, unitIdentifier, chartName, scaling, MeterOrGroup.meter, errorBarState);
-							}
-						}
+					// Convert the meter area into the proper unit if normalizing by area or use 1 if not so won't change reading values.
+					const areaScaling = graphState.areaNormalization ?
+						meterArea * getAreaUnitConversion(meterDataById[meterId].areaUnit, graphState.selectedAreaUnit) : 1;
+					// Divide areaScaling into the rate so have complete scaling factor for readings.
+					const scaling = rateScaling / areaScaling;
+					// Make sure they are there and not being fetched.
+					if (readingsData) {
```
Comment (huss) [inline src/client/app/components/ExportComponent.tsx]: Should this have as lineMeterIsFetching?

File: src/client/app/components/conversion/ConversionViewComponent.tsx (hunk 8 above)
Comment (ChrisMart21) [reply src/client/app/components/conversion/ConversionViewComponent.tsx]: This should be deleted.

File: src/client/app/components/GraphicRateMenuComponent.tsx [hunk 27]
```diff
@@ -22,13 +23,10 @@ export default function GraphicRateMenuComponent() {
 	const dispatch = useDispatch();
```
Comment (huss) [inline src/client/app/components/GraphicRateMenuComponent.tsx]: Most places use useAppDispatch but a few use the old useDispatch. Wondering why?

Comment (ChrisMart21) [reply src/client/app/components/GraphicRateMenuComponent.tsx]: The behavior 'should' be identical & not cause issues, however they all really should be using 'useAppDispatch'.  Must've been overlooked during translation.

File: src/client/app/components/ExportComponent.tsx (hunk 26 above)
Comment (ChrisMart21) [reply src/client/app/components/ExportComponent.tsx]: Line 66 should cover this, but the other cases should also be carefully evaluated. I suppose a check that there is actually meaningful data like readings.length ... etc could be checked here as well. 

I didn't significantly alter the logic in this or most components,  except for how the data is retrieved. 
Upon careful inspection of this code, it appears that many of these checks can be deferred to some already existing selectors, and possibly re-written for easier maintenance which seams like a near-future endeavor.
A refactor should be in order for this and probably many other files.

File: src/client/app/components/HeaderButtonsComponent.tsx [hunk 28]
```diff
@@ -77,15 +76,16 @@ export default function HeaderButtonsComponent() {
 	// Local state for rendering.
 	const [state, setState] = useState(defaultState);
 	// Information on the current user.
-	const currentUser = useSelector((state: State) => state.currentUser.profile);
+	const { profile: currentUser } = useAppSelector(selectCurrentUser);
 	// Tracks unsaved changes.
-	const unsavedChangesState = useSelector((state: State) => state.unsavedWarning.hasUnsavedChanges);
+	// TODO Re-implement AFTER RTK Migration
```
Comment (huss) [inline src/client/app/components/HeaderButtonsComponent.tsx:72]: Is unsaved still used and status of this comment? Does it need to be done later per TODO below?

File: src/client/app/components/HeaderComponent.tsx [hunk 29]
```diff
@@ -3,36 +3,24 @@
...
-		paddingBottom: '5px'
-	};
-	const largeTitleStyle = {
-		display: 'inline-block'
-	};
-	const smallTitleStyle = {
-		display: 'inline-block',
-		marginTop: '10px'
-	};
+	const siteTitle = useAppSelector(state => state.admin.displayTitle);
```
Comment (huss) [inline src/client/app/components/HeaderComponent.tsx]: Another palce where admin state is directly accessed.

File: src/client/app/components/HistoryComponent.tsx [hunk 30]
```diff
@@ -0,0 +1,35 @@
...
+ * @returns Renders a history component with previous and next buttons.
+ */
+export default function HistoryComponent() {
+	const dispatch = useAppDispatch();
+	const backStack = useAppSelector(selectPrevHistory)
+	const forwardStack = useAppSelector(selectForwardHistory)
+
+	return (
+		<div style={{ width: '80%', display: 'flex', flexDirection: 'row', justifyContent: 'space-between' }}>
+			<svg width={20} height={20} viewBox="0 0 10 10" fill="none" xmlns="http://www.w3.org/2000/svg"
```
Comment (huss) [inline src/client/app/components/HistoryComponent.tsx]: xmlns="http://www.w3.org/2000/svg" does not seem necessary when I removed it. Should we have this URL to w3?

File: src/client/app/components/LineChartComponent.tsx [hunk 31]
```diff
@@ -0,0 +1,152 @@
...
+import { selectLineUnitLabel } from '../redux/selectors/plotlyDataSelectors';
+import { graphSlice } from '../redux/slices/graphSlice';
+import { LineReadings } from '../types/readings';
+import translate from '../utils/translate';
+import LogoSpinner from './LogoSpinner';
+import { selectSelectedLanguage } from '../redux/slices/appStateSlice';
+import locales from '../types/locales';
+
+// Stable reference for when there is not data.
+const stableEmptyReadings: LineReadings = {}
```
Comment (huss) [inline src/client/app/components/LineChartComponent.tsx]: Is it okay to move this inside the function? It only seems to be used here but maybe there is an efficienty issue I'm not thinking of.

Comment (ChrisMart21) [reply src/client/app/components/LineChartComponent.tsx]: It is intentionally left outside. Since it is declared outside it will retain a stable object reference. This is there to prevent unnecessary re-rendering when initial data is in flight. Putting it inside will create a new reference each render which defeats its purpose. These stable references could be moved to a different location , or maybe wrapped on a selector if desired. This pattern will show up in a handful of places so we need to decide on this sooner than later.

File: src/client/app/components/ReadingsPerDaySelectComponent.tsx [hunk 32]
```diff
@@ -2,58 +2,45 @@
...
-			return actualReadingInterval
+			actualReadingInterval = endTS.diff(startTS) / 3600000;
 		}
 
-		// Return normal interval
-		return readingInterval;
-	})
+	}
+
+	// Return normal interval
```
Comment (huss) [inline src/client/app/components/ReadingsPerDaySelectComponent.tsx]: First, could this commented out code be removed? Also, I'm unclear on why the new code returns the same value as the old code in this case. Finally, should there be a return above and not be implicit?

File: src/client/app/redux/actions/conversions.ts [hunk 33]
```diff
@@ -1,75 +1,40 @@
...
-import translate from '../utils/translate';
-import * as t from '../types/redux/conversions';
-import { conversionsApi } from '../utils/api';
+/* eslint-disable jsdoc/check-param-names */
+/* eslint-disable @typescript-eslint/ban-ts-comment */
+/* eslint-disable @typescript-eslint/no-unused-vars */
+// @ts-nocheck
+/* eslint-disable jsdoc/require-param */
+
+// TODO Marked For Deletion after RTK migration solidified
```
Comment (huss) [inline src/client/app/redux/actions/conversions.ts]: Not sure used and checking if you are okay with removing this now?

File: src/client/app/redux/actions/graph.ts [hunk 34]
```diff
@@ -0,0 +1,30 @@
+/* This Source Code Form is subject to the terms of the Mozilla Public
+ * License, v. 2.0. If a copy of the MPL was not distributed with this
+ * file, You can obtain one at http://mozilla.org/MPL/2.0/. */
+
+import * as moment from 'moment';
+import { TimeInterval } from '../../../../common/TimeInterval';
+import * as t from '../../types/redux/graph';
+import { ComparePeriod, SortingOrder } from '../../utils/calculateCompare';
+
+export interface LinkOptions {
```
Comment (huss) [inline src/client/app/redux/actions/graph.ts]: I don't see this used. Ok to remove?

File: src/client/app/redux/actions/groups.ts [hunk 35]
```diff
@@ -0,0 +1,193 @@
+// /* This Source Code Form is subject to the terms of the Mozilla Public
+//  * License, v. 2.0. If a copy of the MPL was not distributed with this
+//  * file, You can obtain one at http://mozilla.org/MPL/2.0/. */
+
+// TODO Marked For Deletion after RTK migration solidified
```
Comment (huss) [inline src/client/app/redux/actions/groups.ts]: Ok to remove?

File: src/client/app/redux/actions/meters.ts [hunk 36]
```diff
@@ -1,65 +1,41 @@
...
+import { metersApi } from '../../utils/api';
+import { showErrorNotification, showSuccessNotification } from '../../utils/notifications';
+import translate from '../../utils/translate';
+import { updateCikAndDBViewsIfNeeded } from './admin';
 
-export function receiveMetersDetails(data: t.MeterData[]): t.ReceiveMetersDetailsAction {
-	return { type: ActionType.ReceiveMetersDetails, data };
-}
 
 export function fetchMetersDetails(): Thunk {
```
Comment (huss) [inline src/client/app/redux/actions/meters.ts]: This function is still in a comment in src/client/app/components/csv/ReadingsCSVUploadComponent.tsx but maybe it can be cleaned up and removed. The rest seem to be unused so can delete per TODO above.

File: src/client/app/redux/actions/units.ts [hunk 37]
```diff
@@ -1,61 +1,41 @@
...
+	* License, v. 2.0. If a copy of the MPL was not distributed with this
+	* file, You can obtain one at http://mozilla.org/MPL/2.0/. */
 
-import { ActionType, Thunk, Dispatch, GetState } from '../types/redux/actions';
-import { showSuccessNotification, showErrorNotification } from '../utils/notifications';
-import translate from '../utils/translate';
-import * as t from '../types/redux/units';
-import { unitsApi } from '../utils/api';
-import { updateCikAndDBViewsIfNeeded } from './admin';
+// TODO Marked For Deletion after RTK migration solidified
```
Comment (huss) [inline src/client/app/redux/actions/units.ts]: I don't think this is used. Ok to remove?

File: src/client/app/redux/api/authApi.ts [hunk 38]
```diff
@@ -0,0 +1,60 @@
...
+				url: 'api/login',
+				method: 'POST',
+				body: loginArgs
+			}),
+			// When this mutation is successful, cache stores with these tags are marked as invalid
+			// next time the corresponding endpoint is queried, cache will be ignored and overwritten by a fresh query.
+			// in this case, a user logged in which means that some info for ADMIN meters groups etc.
+			// invalidate forces a refetch to any subscribed components or the next query.
+			invalidatesTags: ['MeterData', 'GroupData']
+			// Listeners for this query (ExtraReducers):
```
Comment (huss) [inline src/client/app/redux/api/authApi.ts]: What is this commented out code for?

File: src/client/app/redux/api/baseApi.ts [hunk 39]
```diff
@@ -0,0 +1,42 @@
...
+		'GroupData',
+		'GroupChildrenData',
+		'Preferences',
+		'Users',
+		'ConversionDetails',
+		'Units'
+	],
+	// Initially no defined endpoints, Use rtk query's injectEndpoints
+	endpoints: () => ({})
+	// Defaults to 60 seconds or 1 minute
```
Comment (huss) [inline src/client/app/redux/api/baseApi.ts]: Keep commented out code?

File: src/client/app/components/groups/EditGroupModalComponent.tsx (hunk 11 above)
Comment (huss) [reply src/client/app/components/groups/EditGroupModalComponent.tsx]: Now that I'm looking at the API, I'm still unsure if this updates too much. The old code determined if other groups were impacted. The new API seems to always invalidate the GroupData. Not sure and other issues with groups.

File: src/client/app/redux/api/metersApi.ts [hunk 40]
```diff
@@ -0,0 +1,114 @@
...
+		}),
+		rawLineReadings: builder.query<RawReadings[], { meterID: number, timeInterval: TimeInterval }>({
+			query: ({ meterID, timeInterval }) => `api/readings/line/raw/meter/${meterID}?timeInterval=${timeInterval.toString()}`
+		})
+	})
+})
+
+
+export const selectMeterDataResult = metersApi.endpoints.getMeters.select()
+
```
Comment (huss) [inline src/client/app/redux/api/metersApi.ts:80]: Is it standard practice to export even if only used in this file? Just trying to understand.

File: src/client/app/redux/api/readingsApi.ts [hunk 41]
```diff
@@ -0,0 +1,156 @@
...
+
+export const readingsApi = baseApi.injectEndpoints({
+	endpoints: builder => ({
+		threeD: builder.query<ThreeDReading, ThreeDReadingApiArgs>({
+			// ThreeD requests only single meters at a time which plays well with default cache behavior
+			// No other properties are necessary for this endpoint
+			// Refer to the line endpoint for an example of an endpoint with custom cache behavior
+			query: ({ id, timeInterval, graphicUnitId, readingInterval, meterOrGroup }) => ({
+				// destructure args that are passed into the callback, and generate/ implicitly return the API url for the request.
+				url: `api/unitReadings/threeD/${meterOrGroup}/${id}?`,
```
Comment (huss) [inline src/client/app/redux/api/readingsApi.ts]: Should there be a ? at the end (below does not have)?

Comment (huss) [reply src/client/app/redux/api/readingsApi.ts:25]: Should there be a ? at the

File: src/client/app/redux/actions/conversions.ts (hunk 33 above)
Comment (ChrisMart21) [reply src/client/app/redux/actions/conversions.ts]: Yep, Should go.

File: src/client/app/redux/actions/graph.ts (hunk 34 above)
Comment (ChrisMart21) [reply src/client/app/redux/actions/graph.ts]: yes, this can/should go

File: src/client/app/redux/api/authApi.ts (hunk 38 above)
Comment (ChrisMart21) [reply src/client/app/redux/api/authApi.ts]: RTK Slices have an optional property called extra reducers, which can listen to any action defined outside of itself. Sometimes its difficult to know which slices are listening to things like rtkQuery actions. In this case its current user slice listens for the match fulfilled action. This was an early on idea- that I'm not certain this will work cleanly. It wasto document the listeners for the endpoint, but should probably go.

File: src/client/app/redux/api/metersApi.ts (hunk 40 above)
Comment (ChrisMart21) [reply src/client/app/redux/api/metersApi.ts:80]: Not sure if there's a standard practice here, or if there are performance implications. Just think its useful to have selectors accessible wherever if need.

File: src/client/app/redux/api/readingsApi.ts (hunk 41 above)
Comment (ChrisMart21) [reply src/client/app/redux/api/readingsApi.ts]: Interesting that it works either way. I'm assuming the fetchBaseQuery is smart enough to sort itself out. I guess it should be omitted since it handles the url generation internally when given a url + params object.

File: src/client/app/redux/componentHooks.ts [hunk 42]
```diff
@@ -0,0 +1,38 @@
...
+// Overloads to support TS key completions
+type TranslateFunction = {
+	(messageID: LocaleDataKey): string;
+	(messageID: string): string;
+}
+
+// usage
+// const translate = useTranslate()
+// translate('myKey')
+export const useTranslate = () => {
```
Comment (huss) [inline src/client/app/redux/componentHooks.ts:27]: I'm trying to figure out how this relates to src/client/app/utils/translate.ts and the fact that some places use one or the other.

File: src/client/app/redux/selectors/adminSelectors.ts [hunk 43]
```diff
@@ -0,0 +1,309 @@
...
+	unitData => {
+		let possibleMeterUnits = new Set<UnitData>();
+		// The meter unit can be any unit of type meter.
+		unitData.forEach(unit => {
+			if (unit.typeOfUnit == UnitType.meter) {
+				possibleMeterUnits.add(unit);
+			}
+		});
+		// Put in alphabetical order.
+		possibleMeterUnits = new Set(_.sortBy(Array.from(possibleMeterUnits), unit => unit.identifier.toLowerCase(), 'asc'));
```
Comment (huss) [inline src/client/app/redux/selectors/adminSelectors.ts:51]: This is not a change but I noticed in src/client/app/redux/api/unitsApi.ts that the sorting includes an accent term and localCompare. There are other places where the way we sort differs. Do you think they should be consistent? If so, we should see if a function(s) can be used to do this in an easier way.

File: src/client/app/redux/selectors/adminSelectors.ts [hunk 44]
```diff
@@ -0,0 +1,309 @@
...
+		(_state, meterDetails: MeterData) => meterDetails.unitId,
+		(_state, meterDetails: MeterData) => meterDetails.defaultGraphicUnit
+	],
+	(possibleGraphicUnits, possibleMeterUnits, unitId, defaultGraphicUnit) => {
+		// Graphic units compatible with currently selected unit
+		const compatibleGraphicUnits = new Set<UnitData>();
+		// Graphic units incompatible with currently selected unit
+		const incompatibleGraphicUnits = new Set<UnitData>();
+		// If unit is not 'no unit'
+		if (unitId != -99) {
```
Comment (huss) [inline src/client/app/redux/selectors/adminSelectors.ts:97]: This is used for both edit and create. For create there used to be a separate test for -999. I'm noting since this may need to change to get the other code to allow no unit. Same below.

File: src/client/app/redux/selectors/adminSelectors.ts [hunk 45]
```diff
@@ -0,0 +1,309 @@
...
+			enabled: false,
+			displayable: false,
+			meterType: '',
+			url: '',
+			timeZone: '',
+			// String type conflicts with MeterDataType GPSPoint
+			gps: '',
+			// Defaults of -999 (not to be confused with -99 which is no unit)
+			// Purely for allowing the default select to be "select a ..."
+			unitId: -99,
```
Comment (huss) [inline src/client/app/redux/selectors/adminSelectors.ts]: -99 vs -999 here too.

File: src/client/app/redux/selectors/threeDSelectors.ts [hunk 46]
```diff
@@ -0,0 +1,47 @@
...
+// Memoized Selectors
+export const selectThreeDComponentInfo = createSelector(
+	selectThreeDMeterOrGroupID,
+	selectThreeDMeterOrGroup,
+	selectMeterDataById,
+	selectGroupDataById,
+	(id, meterOrGroup, meterDataById, groupDataById) => {
+		//Default Values
+		let meterOrGroupName = 'Unselected Meter or Group'
+		let isAreaCompatible = true;
```
Comment (huss) [inline src/client/app/redux/selectors/threeDSelectors.ts:27]: My reading of the code indicates this must be set by selectNameFromEntity so this value does not matter. Wanted to verify that is correct. If so, I think we should set to empty string (or comment).

File: src/client/app/redux/selectors/uiSelectors.ts [hunk 47]
```diff
@@ -0,0 +1,545 @@
...
+		// Get the new min and max times, in seconds, from the slider box
+		const newMinXTimestamp = Math.floor(minTimeStamp + (secondsPerPixel * sliderMinX));
+		const newMaxXTimestamp = Math.floor(minTimeStamp + (secondsPerPixel * sliderMaxX));
+		// The newMin/MaxTimestamp is equivalent to a Unix time in milliseconds. Thus, it will
+		// shift with timezone. It isn't clear if we want it in local or UTC. It depends on what
+		// plotly does. Here it is assumed that local is what is desired. This seems to work
+		// and not shift the graphs x-axis so using.
+		return new TimeInterval(moment(newMinXTimestamp), moment(newMaxXTimestamp)).toString();
+	} else {
+		return 'all'
```
Comment (huss) [inline src/client/app/redux/selectors/uiSelectors.ts]: This used to throw an error. I can see that all would graph the full range but is it covering up an error? Should we log here or is it normal?

Comment (ChrisMart21) [reply src/client/app/redux/selectors/uiSelectors.ts]: I think this approach needs to be reworked. We need to tap into the plotly component callbacks to retrieve and manage this value.
 I haven't got around to implementing this and kept this in as a reminder/to cover up errors for the time being.

File: src/client/app/redux/slices/graphSlice.ts [hunk 48]
```diff
@@ -0,0 +1,380 @@
...
+			if (cleared) {
+				const clearedMeterOrGroups = meta.removedValues;
+				// A Select has been cleared(all values removed with clear)
+				// use the first index of cleared items to check for meter or group
+				isAMeter = clearedMeterOrGroups[0].meterOrGroup === MeterOrGroup.meters
+				// if a meter clear meters, else clear groups
+				isAMeter ? current.selectedMeters = [] : current.selectedGroups = []
+
+			}
+			if (valueRemoved) {
```
Comment (huss) [inline src/client/app/redux/slices/graphSlice.ts]: Are these mutually exclusive? If so, should it be else if for these?

File: src/client/app/types/locales.ts [hunk 49]
```diff
@@ -2,7 +2,7 @@
  * License, v. 2.0. If a copy of the MPL was not distributed with this
  * file, You can obtain one at http://mozilla.org/MPL/2.0/. */
 
-export default class Locales{
+export default class locales{
```
Comment (huss) [inline src/client/app/types/locales.ts]: Normally class names are capitalized. Is this to avoid the same name from Plotly or something else? Maybe we should refactor name if this is the case.

File: src/client/app/types/redux/state.ts [hunk 50]
```diff
@@ -16,15 +15,15 @@ import { CurrentUserState } from './currentUser';
...
-import { OptionsState } from './options';
+import { AppState } from 'redux/slices/appStateSlice';
 
 export interface State {
+	appState: AppState;
 	meters: MetersState;
 	readings: {
 		line: LineReadingsState;
 		bar: BarReadingsState;
 		compare: CompareReadingsState;
```
Comment (huss) [inline src/client/app/types/redux/state.ts:26]: Just curious why 3D was removed from here.

File: src/client/app/utils/hasPermissions.ts [hunk 51]
```diff
@@ -21,5 +21,7 @@ export function hasPermissions(user: UserRole, compareTo: UserRole): boolean {
  * @returns Whether or not user is an admin
  */
 export function isRoleAdmin(user: UserRole): boolean {
+	// TODO Already Converted to a selector
```
Comment (huss) [inline src/client/app/utils/hasPermissions.ts]: The only place this is used is src/client/app/components/HeaderButtonsComponent.tsx. The comment seems out of date since that function does not exist. I think we should purge the last use and get rid of this but want to check with you on the best way to do that.

File: src/server/test/web/readingsData/expected_bar_ri_15_mu_kWh_gu_kWh_st_-inf_et_inf_bd_75.csv [hunk 52]
```diff
@@ -0,0 +1,2 @@
+reading,start time,end time
```
Comment (huss) [inline src/server/test/web/readingsData/expected_bar_ri_15_mu_kWh_gu_kWh_st_-inf_et_inf_bd_75.csv]: Not sure why this is listed as a change but same as current development so should be fine. Just noting.

File: src/server/test/web/readingsBarMeterQuantity.js [hunk 53]
```diff
@@ -94,9 +94,23 @@ mocha.describe('readings API', () => {
                     // Check that the API reading is equal to what it is expected to equal
                     expectReadingToEqualExpected(res, expected);
                 });
-
-                // Add B5 here
-
+                mocha.it('B5: 75 day bars for 15 minute reading intervals and quantity units with +-inf start/end time & kWh as kWh', async () => {
```
Comment (huss) [inline src/server/test/web/readingsBarMeterQuantity.js]: Another change that already in development so noting.

File: src/client/app/components/groups/GroupsDetailComponent.tsx [hunk 54]
```diff
@@ -3,77 +3,29 @@
...
-		// You need the basic group state loaded since going to modify.
-		if (groupsStateLoaded) {
-			// Get all groups' meter and group immediate children into state. Since all modals done for all groups
-			// we get them all here.
-			dispatch(fetchAllGroupChildrenIfNeeded());
-		}
-		// In case the group state was not yet loaded you need to do this again.
-	}, [groupsStateLoaded, groupsAllChildrenLoaded]);
+	// page may contain admin info so verify admin status while admin is authenticated.
+	authApi.useTokenPollQuery(undefined, { skip: !isAdmin, pollingInterval: authPollInterval })
```
Comment (huss) [inline src/client/app/components/groups/GroupsDetailComponent.tsx]: I'm wondering why tis is not in admin, conversion & unit (and maps at some point) pages? Maybe others.

File: src/client/app/redux/api/metersApi.ts (hunk 40 above)
Comment (huss) [reply src/client/app/redux/api/metersApi.ts:80]: Maye see https://stackoverflow.com/questions/76705375/does-exporting-a-module-and-never-importing-it-anywhere-affect-performance

File: src/client/app/components/groups/GroupsDetailComponent.tsx (hunk 54 above)
Comment (ChrisMart21) [reply src/client/app/components/groups/GroupsDetailComponent.tsx]: Admin outlet has this polling effect so any of it's children also inherit the behavior.

Meter and group pages are kinda different because they modify behaviors based on auth status so they live outside the adminOutlet and explicitly need the polling added here

File: src/client/app/components/csv/MetersCSVUploadComponent.tsx (hunk 10 above)
Comment (huss) [reply src/client/app/components/csv/MetersCSVUploadComponent.tsx]: fixed

File: src/client/app/components/MapChartComponent.tsx (hunk 13 above)
Comment (huss) [reply src/client/app/components/MapChartComponent.tsx]: done

File: src/client/app/components/router/GraphLinkComponent.tsx (hunk 15 above)
Comment (huss) [reply src/client/app/components/router/GraphLinkComponent.tsx]: gone, map link elsewhere

File: src/client/app/containers/CompareChartContainer.ts (hunk 18 above)
Comment (huss) [reply src/client/app/containers/CompareChartContainer.ts:209]: Just noting that we don't want to zoom on compare so this is fine.

File: src/client/app/components/BarChartComponent.tsx (hunk 20 above)
Comment (huss) [reply src/client/app/components/BarChartComponent.tsx]: done

File: src/client/app/components/ChartSelectComponent.tsx (hunk 24 above)
Comment (huss) [reply src/client/app/components/ChartSelectComponent.tsx:45]: looks good

File: src/client/app/redux/actions/groups.ts (hunk 35 above)
Comment (huss) [reply src/client/app/redux/actions/groups.ts]: done

File: src/client/app/redux/actions/meters.ts (hunk 36 above)
Comment (huss) [reply src/client/app/redux/actions/meters.ts]: done

File: src/client/app/redux/actions/units.ts (hunk 37 above)
Comment (huss) [reply src/client/app/redux/actions/units.ts]: done

File: src/client/app/redux/api/metersApi.ts (hunk 40 above)
Comment (huss) [reply src/client/app/redux/api/metersApi.ts:80]: Maybe see https://stackoverflow.com/questions/76705375/does-exporting-a-module-and-never-importing-it-anywhere-affect-performance. I'm not sure which way to go on this.

File: src/client/app/redux/api/readingsApi.ts (hunk 41 above)
Comment (huss) [reply src/client/app/redux/api/readingsApi.ts]: Removed.

File: src/client/app/components/groups/EditGroupModalComponent.tsx (hunk 11 above)
Comment (huss) [reply src/client/app/components/groups/EditGroupModalComponent.tsx]: It is true that this invalidates the entire group redux state. However, it is possible that the edit of one group impacts another that includes it. OED could check if the full update is needed but that would require changing how group state is acquired. Given this isn't done very often and only by admins, OED will not make this change now (or maybe ever). This same philosophy will be used for all such changes/invalidations for admin work.

File: src/client/app/redux/api/groupsApi.ts (hunk 14 above)
Comment (huss) [reply src/client/app/redux/api/groupsApi.ts]: Changed to error popup.

File: src/client/app/components/DateRangeComponent.tsx (hunk 25 above)
Comment (huss) [reply src/client/app/components/DateRangeComponent.tsx]: I added a small comment to document.

File: src/client/app/components/GraphicRateMenuComponent.tsx (hunk 27 above)
Comment (huss) [reply src/client/app/components/GraphicRateMenuComponent.tsx]: I replaced all uses with useAppDispatch.

File: src/client/app/components/LineChartComponent.tsx (hunk 31 above)
Comment (huss) [reply src/client/app/components/LineChartComponent.tsx]: Clarified comment

File: src/client/app/types/locales.ts (hunk 49 above)
Comment (ChrisMart21) [reply src/client/app/types/locales.ts]: Reverted back to UpperCase.

File: src/client/app/components/HeaderComponent.tsx (hunk 29 above)
Comment (ChrisMart21) [reply src/client/app/components/HeaderComponent.tsx]: Corrected.

File: src/client/app/redux/selectors/uiSelectors.ts (hunk 47 above)
Comment (ChrisMart21) [reply src/client/app/redux/selectors/uiSelectors.ts]: This has been pushed back until after this PR. Graphs are going to all be reworked to track all necessary attrributes will live in Redux( including the range Slider interval) Resolving for now.

File: src/client/app/redux/api/authApi.ts (hunk 38 above)
Comment (ChrisMart21) [reply src/client/app/redux/api/authApi.ts]: removing for now since not standard.

File: src/client/app/redux/api/baseApi.ts (hunk 39 above)
Comment (ChrisMart21) [reply src/client/app/redux/api/baseApi.ts]: Deleted, can change if needed.

File: src/client/app/redux/api/metersApi.ts (hunk 40 above)
Comment (ChrisMart21) [reply src/client/app/redux/api/metersApi.ts:80]: I think this is a non-critical issue. I will deffer this to some later PR if desired.

File: src/client/app/components/BarChartComponent.tsx (hunk 22 above)
Comment (ChrisMart21) [reply src/client/app/components/BarChartComponent.tsx]: Fixed For now.

File: src/client/app/components/HeaderButtonsComponent.tsx (hunk 28 above)
Comment (ChrisMart21) [reply src/client/app/components/HeaderButtonsComponent.tsx:72]: Unsaved warning needs an overall update and is planned to get re-implemented post-rtk migration.

File: src/client/app/redux/selectors/threeDSelectors.ts (hunk 46 above)
Comment (ChrisMart21) [reply src/client/app/redux/selectors/threeDSelectors.ts:27]: This is correct. Not is an empty string instead.

File: src/client/app/redux/slices/graphSlice.ts (hunk 48 above)
Comment (ChrisMart21) [reply src/client/app/redux/slices/graphSlice.ts]: yes, only one event should happpen per reducer pass. elifs were used in the later half of this reducer, but didn't seem to make it up here. Fixed

File: src/client/app/utils/hasPermissions.ts (hunk 51 above)
Comment (ChrisMart21) [reply src/client/app/utils/hasPermissions.ts]: Yeah, these are essentially selectors. This file is legacy, and will be deleted.

File: src/client/app/types/redux/state.ts (hunk 50 above)
Comment (ChrisMart21) [reply src/client/app/types/redux/state.ts:26]: This is old state, which is only used in maps. 3d was the first to implement RTKQ, so was removed here a while ago. But this all should go soon, so not of much importance. Resolving convo.

File: src/client/app/components/ReadingsPerDaySelectComponent.tsx (hunk 32 above)
Comment (ChrisMart21) [reply src/client/app/components/ReadingsPerDaySelectComponent.tsx]: Commented out code, removed.

Comment (ChrisMart21) [reply src/client/app/components/ReadingsPerDaySelectComponent.tsx]: What do you mean by old code. vs new code. I'm unsure there's a difference between the two iterations in this context. Could you expand on this?

File: src/client/app/redux/selectors/adminSelectors.ts (hunk 44 above)
Comment (huss) [reply src/client/app/redux/selectors/adminSelectors.ts:97]: I think this is resolved. Could @ChrisMart21 verify.

File: src/client/app/redux/selectors/adminSelectors.ts (hunk 45 above)
Comment (huss) [reply src/client/app/redux/selectors/adminSelectors.ts]: Changes have fixed.

File: src/client/app/redux/componentHooks.ts (hunk 42 above)
Comment (huss) [reply src/client/app/redux/componentHooks.ts:27]: Need to resolve store more generally so will address in future.

File: src/client/app/redux/selectors/adminSelectors.ts (hunk 43 above)
Comment (huss) [reply src/client/app/redux/selectors/adminSelectors.ts:51]: Will get consistent in future.

File: src/client/app/redux/selectors/adminSelectors.ts (hunk 44 above)
Comment (ChrisMart21) [reply src/client/app/redux/selectors/adminSelectors.ts:97]: Is resolved with recent create meter modal updates.

**Comment by huss** [comment]
I want to express my deep thanks to @ChrisMart21 for initiating and completing the migration of OED to the Redux Toolkit and Query system. This not only gets OED up to the latest Redux usage but adds a number of new features such as history of graphics. This is a substantial step in OED keeping current with technology and reducing our technical debt. Many thanks.

**Review by huss — APPROVED** [review]
Thanks to @ChrisMart21 for another substantial contribution. All the comments have been addressed and testing finds the code works as expected. It is ready to merge.
