### PR TITLE
fix login/out header buttons and automatic logout

### LINKED ISSUE #692: no login button when admin login times out
### Describe the bug

If your token times out for admin login, all the menus for admin go away but you still have the logout button instead of the normal login button when you are logged out.

### To Reproduce

Login as an admin and wait about a day and you will see this if you reload the OED page. It may be possible to reproduce this at any time by modifying the token stored for an admin login.

### Expected behavior

When the admin menus are not present, OED should display the login and not the logout button.

### Additional context

The workaround for now it to click the logout button. The login button appears so you can login as expected.

### LINKED ISSUE #815: Non-admin users cannot log out
### Describe the bug

PR #807 changed the logic for which header buttons are displayed. This introduced a bug in which non-admin users (such as those with CSV permissions) are unable to log out.

### To Reproduce

1. Log in as a non-admin user

### Expected behavior

A log out button should display whenever a user is logged in

### Screenshots

image

### Additional context

I have discovered and made a fix for this as part of my work on #692, just submitting this for reference.

### LINKED ISSUE #816: Non-admin users can view admin pages
### Describe the bug

Non-admin users (such as those with CSV permissions) can view admin only pages as long as they have a valid token.

### To Reproduce

1. Log in as a non-admin user
2. Navigate directly to an admin page using a url

### Expected behavior

Users should only be able to access pages that they are allowed to.

### Screenshots

image

### Additional context

I have discovered and made a fix for this as part of my work on https://github.com/OpenEnergyDashboard/OED/issues/692, just submitting this for reference.

### PR DESCRIPTION
**Pull request by spearec**
# Description
This PR fixes issues with automatic logout for users with invalid tokens and improper display of login/logout header buttons. It also adds a more clear message to users when they are logged out because their token has expired.

Fixes #692
Fixes #815 
Fixes #816 
Partly Addresses #817 

## Type of change
- [ ] Note merging this changes the node modules
- [ ] Note merging this changes the database configuration.
- [ ] This change requires a documentation update

## Checklist
- [x] I have followed the [OED pull request](https://openenergydashboard.github.io/developer/pr.html) ideas
- [x] I have removed text in ( ) from the issue request

## Limitations
This PR makes the issues outlined in #817 invisible, but they still exist.

### CODE REVIEW

File: src/client/app/components/RouteComponent.tsx [hunk 1]
```diff
@@ -54,31 +54,36 @@ export default class RouteComponent extends React.Component<RouteProps> {
...
 	 * @param requiredRole The role that is necessary to access a page route
 	 * @param component The component of the page redirecting
-	 * @returns middleware that requires proper role and authentication for a page route
+	 * @returns The page route to continue to (component or home)
 	 */
 	public requireRole(requiredRole: UserRole, component: JSX.Element) {
-		// Redirect route to login page if the auth token does not exist
-		if (!hasToken()) {
-			return <Redirect to='/login'/>;
+		// Redirect route to login page if the auth token does not exist or if the user is not a csv role
```
Comment (huss) [inline src/client/app/components/RouteComponent.tsx]: I'm unclear on why this comment has csv role since the code seems to be using value passed? Am I missing something?

File: src/client/app/components/HeaderButtonsComponent.tsx [hunk 2]
```diff
@@ -37,14 +36,15 @@ export default class HeaderButtonsComponent extends React.Component<HeaderButton
...
+		const renderLoginButton = role === null;
+		const renderLogoutButton = role !== null;
 		const shouldHomeButtonDisabled = getPage() === '';
 		const shouldAdminButtonDisabled = getPage() === 'admin';
 		const shouldGroupsButtonDisabled = getPage() === 'groups';
 		const shouldMetersButtonDisabled = getPage() === 'meters';
 		const shouldMapsButtonDisabled = getPage() === 'maps';
 		const shouldCSVButtonDisabled = getPage() === 'csv';
-		const renderCSVButton = Boolean(role && hasPermissions(role, UserRole.CSV));
+		const renderCSVButton =  Boolean(role && hasPermissions(role, UserRole.CSV));
```
Comment (huss) [inline src/client/app/components/HeaderButtonsComponent.tsx]: extra space before Boolean.

File: src/client/app/translations/data.js [hunk 3]
```diff
@@ -201,7 +201,8 @@ const localeData = {
 		"insufficient.readings": "Insufficient readings data to process comparison for ",
 		"invalid.email.password": "Invalid email/password combination",
 		"invalid.number": "Please submit a valid number (between 0 and 2.0)",
-		"invalid.token.login.or.logout": "Token has expired. Either log in again, or log out.",
+		"invalid.token.login": "Token has expired. Please log in again.",
+		"invalid.token.login.admin": "Token has expired. Please log in again to view this page.",
```
Comment (huss) [inline src/client/app/translations/data.js:205]: This needs to be added to es and fr sections where it is fine to use the needed text in front as shown in others.

File: src/client/app/utils/hasPermissions.ts [hunk 4]
```diff
@@ -2,6 +2,7 @@
  * License, v. 2.0. If a copy of the MPL was not distributed with this
  * file, You can obtain one at http://mozilla.org/MPL/2.0/. */
 
+
```
Comment (huss) [inline src/client/app/utils/hasPermissions.ts]: I think an extra blank line was added.

**Review by huss — CHANGES_REQUESTED** [review]
Thanks to @spearec for not only addressing the original issue but being careful and thereby finding several other issues that are addressed. Testing indicates the code works as expected and addresses the linked issues. I have made a few comments that I hope are easy to address.

File: src/client/app/components/RouteComponent.tsx (hunk 1 above)
Comment (spearec) [reply src/client/app/components/RouteComponent.tsx]: That would be a typo on my part, since the only use of that function right now is for the csv page.

**Comment by spearec** [comment]
@huss I made the requested changes. I used the existing Spanish and French strings when possible, but some parts still need to be translated.

**Review by huss — APPROVED** [review]

**Comment by huss** [comment]
> @huss I made the requested changes. I used the existing Spanish and French strings when possible, but some parts still need to be translated.

Thanks to @spearec for the quick changes. All looks good and this is ready to merge.
